"""Publish only aggregate evidence; never copy payloads, request IDs or run credentials.
Run from the retained experiment root: python3 docs/build_80k_report.py
The published copy documents the source; private source artifacts are prerequisites.
"""
from pathlib import Path
import datetime, hashlib, html, json, shutil
R=Path('/mnt/HPC/tom/pd-80k-rerun-20260914')
O=Path('/home/tom/maas_docs/docs/glm53-gb300-ttft-tpot-optimization')
E=O/'80k-evidence';E.mkdir(exist_ok=True)
esc=html.escape
load=lambda p:json.loads(p.read_text())
def dump(name,x): (E/name).write_text(json.dumps(x,indent=2)+'\n')
def table(headers,rows):
 return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+esc(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def link(url,label):return '<a href="'+esc(url)+'">'+esc(label)+'</a>'
def code(x):return '<code>'+esc(str(x))+'</code>'
def num(x,d=3):return f'{x:,.{d}f}' if x is not None else '—'
sections=[]
def section(i,t,c):sections.append((i,t,c))
keys=['run_id','state','expected_requests','requests','recorded_request_ids_unique_and_in_candidate','runtime_vs_prepared_token_count_mismatches','runtime_vs_prepared_count_delta','known_usage_requests','meaningful_requests','protocol_success_without_meaningful_generation','ttft_percentiles_s','tpot_ms','otps_finite_quantiles','otps_finite_count','valid_ttft_chart_points','points_p50_ge4s','points_p50_ge4s_during_admissions','points_p50_ge4s_during_drain','worst_ttft_point','worst_tpot_point','tpot_requests_gt40ms','tpot_requests_gt80ms','tpot_zero_span','tpot_threshold_fractions','input_tokens','cached_tokens','uncached_tokens','hit_ratio','measured_mean_input','last_admission_s','last_completion_s','admission_minutes','generator','bad_ttft_points','data_hashes','acceptance_note']
results={};charts={}
for name,label in [('run-2p1d-80k','2P4 + D8 · 80K'),('run-1p1d-80k','1P4 + D8 · 80K original outputs')]:
 a=R/name
 if not (a/'ANALYSIS.json').exists():continue
 x=load(a/'ANALYSIS.json');public={k:x[k] for k in keys};results[name]=public;dump(name+'.json',public)
 ts=load(R/'evidence'/x['run_id']/'timeseries.json')['distribution_sliding']
 charts[label]={'run_id':x['run_id'],'points':[[p['t'],p['ttft']['p50'],p['tpot']['p99'],p['n_samples']] for p in ts['points']]}
 for f in ['live-rolling-duration-audit.json','live-rolling-audit.json']:
  y=load(a/'replay'/f)
  if f=='live-rolling-duration-audit.json':y={k:v for k,v in y.items() if k!='spans'}
  # Boundary auditor includes example windows only, never request bodies; reduce to totals.
  else:
   y={k:y[k] for k in ['schema','probes','input_plan_sha256','acceptance_policy','method','numeric_only','finite_capacity_or_completion_model','failed_probes','passed','prompt_tokens','uncached_tokens','hit_ratio']}
  dump(name+'-'+f,y)
for att in ['56','57']:
 p=O/('latency-att'+att+'.json')
 x=load(p)
 # Main historical chart data is extracted as aggregates from the already published page.
main=(O/'index.html').read_text();start='<script type="application/json" id="chart-data">'
if start in main:
 old=json.loads(main.split(start,1)[1].split('</script>',1)[0].replace('<\\/','</'))
 for label,x in old.items():
  if label in ['20260913_211342','20260913_215025']:
   charts[('ATT56 · 2P4 + D8 · 50.7K' if label=='20260913_211342' else 'ATT57 · 1P4 + D8 · 50.7K original outputs')]=x
# Dataset metadata is explicit and excludes source IDs and request payloads.
datasets={'2P4+D8':{'candidate':'dataset-2p1d-candidate29','requests':7504,'warmup':400,'mean_input':79987.82476012793,'whole_pack_mean':78558.44167510121,'input_tokens':600228637,'uncached_tokens':60027997,'dataset_id':'dataset-e9d268c61c5a8f296e570879','profile_id':'profile-33f170cbe5d5f35548243465','numeric_probes':40486,'numeric_failures':0,'output_policy':'max_tokens=20'},'1P4+D8':{'candidate':'dataset-1p1d-candidate01','requests':3760,'warmup':100,'mean_input':79839.10664893617,'whole_pack_mean':79415.82279792747,'input_tokens':300195041,'uncached_tokens':29943969,'dataset_id':'dataset-52e2dd364ff25ef9dea81a1d','profile_id':'profile-1d54634d80f68f52252c4f09','numeric_probes':20254,'numeric_failures':0,'output_policy':'original; request_max_tokens=null'}}
for x in datasets.values():
 c=load(R/x['candidate']/'candidate.json');assert len(c['measured_requests'])==x['requests'];assert sum(r['length'] for r in c['measured_requests'])==x['input_tokens']
 x['mean_input']=x['input_tokens']/x['requests'];x['whole_pack_mean']=(x['input_tokens']+sum(r['length'] for r in c['warmup_requests']))/(x['requests']+x['warmup'])
 x['plan_sha256']=hashlib.sha256((R/x['candidate']/'candidate.json').read_bytes()).hexdigest()
dump('datasets.json',datasets);dump('chart-data.json',charts)
dump('missing-generation-shapes.json',load(R/'run-2p1d-80k/MISSING-GENERATION-SHAPES.json'))
dump('2p-prefill-counters.json',load(R/'run-2p1d-80k/PREFILL-COUNTER-SUMMARY.json'))
if (R/'LATEST-CAPSULE.json').exists():dump('reproduction-capsule.json',load(R/'LATEST-CAPSULE.json'))
now=datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).strftime('%Y-%m-%d %H:%M Singapore')
intro='<p>These reruns replace the earlier roughly 50.7K-input subsets with distinct original Zhipu requests averaging approximately 80K tokens. Input and uncached traffic targets, token-weighted cache hit and finite-cache constraints are retained.</p>'
rows=[]
for arm,label in [('run-2p1d-80k','2P4 + D8'),('run-1p1d-80k','1P4 + D8, original outputs')]:
 x=results.get(arm)
 if not x:rows.append([label,'In progress','—','—','—','—']);continue
 rows.append([link('http://43.156.43.133:31019/replay/runs/'+x['run_id']+'/report',label),esc(x['state']),num(x['ttft_percentiles_s']['p50'])+' / '+num(x['ttft_percentiles_s']['p99']),num(x['worst_ttft_point']['ttft']['p50']/1000),num(x['tpot_ms']['p99']),str(x['meaningful_requests'])+' / '+str(x['expected_requests'])])
intro+=table(['Run','State','TTFT P50 / P99 (s)','Worst 20s P50 (s)','TPOT P99 (ms)','Meaningful / planned'],rows)
intro+='<p class="note"><strong>2P: median objective passed; full acceptance withheld.</strong> All 603 eligible 20-second completion windows stayed below 4s (worst 3.601s). Four protocol-success requests lacked meaningful generation, TPOT tails remain, and some live uncached-traffic windows exceeded tolerance. The generator was valid. Those are separate gates.</p>'
if 'run-1p1d-80k' not in results:intro+='<p>The 1P row is pending. Warmup values are not presented as measured results.</p>'
else:
 x=results['run-1p1d-80k'];out=load(R/'run-1p1d-80k/OUTPUT-DISTRIBUTION.json');dump('1p-output-distribution.json',out)
 intro+='<p class="note"><strong>1P: complete and generator-valid, but the strict median objective narrowly missed.</strong> All 3,760 requests produced meaningful output. Twelve consecutive chart points at elapsed 332–343s had 20s TTFT P50 at or above 4s; worst 4.075s with 127 completions. No drain window failed. TPOT P99 was 23.905ms, with no request above 40ms; worst window TPOT P99 was 31.693ms.</p>'
 intro+='<p>The 1P replay produced 4,147,427 output tokens (mean 1,103; maximum 80,000), versus 4,060,571 in historical ATT57. Realized Decode output pressure remained comparable despite fewer, longer-input requests. The last response completed at 851.755s.</p>'

intro+='<p>No new serving optimization was introduced for these reruns. This is a workload comparison using the pinned historical overlays; it is not evidence of an isolated code-change gain.</p>'
section('results','80K rerun results',intro)
section('datasets','Dataset construction',table(['Property','2P4 + D8','1P4 + D8'],[
 ['Input / uncached target TPM','60M / 6M','30M / 3M'],
 ['Measured requests / warmup','7,504 / 400','3,760 / 100'],
 ['Mean input, measured',num(datasets['2P4+D8']['mean_input']),num(datasets['1P4+D8']['mean_input'])],
 ['Mean input, including warmup',num(datasets['2P4+D8']['whole_pack_mean']),num(datasets['1P4+D8']['whole_pack_mean'])],
 ['Prepared token-weighted cache hit','89.9991%','90.0252%'],
 ['All-boundary rolling-minute probes / failures','40,486 / 0','20,254 / 0'],
 ['Admission duration','600s','600s'],['Output policy','20-token cap','Original output settings; no override']])+
 '<p>The measured-request mean is the 80K target. The catalog also includes shorter warmup requests. Constant TPM means each rolling 60-second window meets input ±1% and modeled uncached ±5%; it does not mean identical instantaneous arrivals.</p><p>Both packs come from the 66,167-request July 24 Zhipu corpus. There is no padding, truncation, repeated-request loop or synthetic cache prefix. Every compressed payload frame was copied verbatim and verified. All 11,764 selected token sequences across both packs matched the original prepared source. An independent oracle hashed original token bytes at 64-token prefix boundaries and reproduced every planned ideal prefix hit.</p><p>The 2P selection search retained all unsuccessful variants. Candidate 29 passed; candidate 30 did not. The selector favors original session continuations that support the 80K mean while retaining minimum session spacing, producer delays, ancestry, diversity and cache limits.</p>')
section('cache','Finite cache and live traffic', '<p>Prefill has 9,252,096 logical GPU tokens per PP stage and 13,878,208 inclusive local host tokens per worker. PP stages are not additive capacity. The shared Mooncake Store has 1,300GiB; it was verified empty before each warmup.</p><p>The independent 2P sensitivity model passes with 11.103M local tokens per Prefill and 20M shared logical tokens at 2–5s publication delay. It fails without L3 and with 10s publication delay. The latter reaches 7.123M uncached TPM. These are modeling limits, not a native router simulation or a runtime guarantee. The 1P candidate passes 13.878M and 11.103M scenarios; one 9.252M timing scenario fails.</p><p>PP0 scrape-aligned counters show 29.993M / 30.958M newly computed tokens on Prefill 132 / 151 over approximately 600s. L3 served 1.165M / 0.706M prefix tokens; sampled queues peaked at 15 / 16 requests. Both host caches reached 13,878,144 tokens. These counters establish actual L3 use and fairly balanced compute, with scrape-boundary uncertainty.</p><p>Observed 2P input was 600,228,806 tokens and uncached work 61,061,254 tokens: 6.106M uncached TPM and 89.8270% cache hit. Rolling uncached traffic ranged from 5.910M to 6.411M. The exact duration audit finds 30.309s outside ±5%, or 5.613% of the 540s window-start domain. Input ±1% was exceeded for just 0.00447s. These live departures are retained explicitly.</p><p>Prepared/server input counts differ by +1 on 169 requests. The historical ATT56/ATT57 runs also had +1 differences on 305/63 requests. The underlying cause is not established.</p>')
if 'run-1p1d-80k' in results:
 i,title,content=sections[-1]
 content+='<p><strong>1P live traffic:</strong> 300,195,132 input tokens and 29,940,156 uncached tokens, or 90.0264% hit. All uncached rolling windows stayed within ±5% (2.879M–3.114M). Three of 20,280 boundary probes exceeded input ±1%; the exact affected duration was 0.062021s of the 540s window-start domain. The departure is small but is not discarded. Prepared/server counts differed by +1 on 91 requests.</p>'
 sections[-1]=(i,title,content)
section('charts','Latency through admission and drain','<p>Trailing 20-second <strong>completion</strong> cohorts; client meaningful-generation TTFT. Windows require at least three protocol-success completions. Hover for values. The 600s line marks the end of admissions; drain remains included.</p><label for="run-select">Run </label><select id="run-select">'+''.join('<option>'+esc(k)+'</option>' for k in charts)+'</select><div class="chart"><h3>TTFT P50 · seconds</h3><svg id="ttft" viewBox="0 0 900 255" role="img" aria-label="TTFT P50 over time"></svg></div><div class="chart"><h3>TPOT P99 · milliseconds</h3><svg id="tpot" viewBox="0 0 900 255" role="img" aria-label="TPOT P99 over time"></svg></div><p id="readout" aria-live="polite">Move over a chart to inspect a completion window.</p>')
section('interpretation','Acceptance and comparison', '<p>Use raw client timing for request latency. Whole-run TTFT P50/P75/P90/P99 targets are 4/8/12/30s; the investigation additionally requires every eligible 20s completion-window median below 4s, including drain. TPOT P50/P90/P99 targets are 18/33/40ms. OTPS targets were specified as 55/30/25 tokens/s; low-rate tails correspond to high TPOT tails, so ascending percentile labels must not be blindly inverted.</p><p>The new 2P whole-run TTFT is 2.790/3.376/3.950/5.219s and TPOT is 11.003/17.530/23.238ms. Nineteen requests have TPOT above 40ms, fifteen above 80ms, and worst 20s TPOT P99 is 133.139ms. There are 2,759 zero-span TPOT observations; they do not establish finite OTPS.</p><p>All four missing-generation requests were included in a conservative median sensitivity bound. Even assigning unknown latencies above all observed latencies leaves every window median below 4s. This does not repair missing-response coverage or identify their actual TTFT. Alex’s empty-output counter alone misses this condition. All four ended at length 20 with DONE and reported 20 output tokens, but zero observed generation. Usage-reconciled token timestamps cannot establish meaningful TTFT; the exact parser/model cause remains unproven.</p><p>Historical ATT56 had TTFT P50/P99 2.839/4.949s and worst window median 3.898s. The new 80K workload has a slightly lower median and worse global P99. Historical ATT57 had TTFT P50/P99 3.021/15.360s, with two drain windows at or above 4s (worst 4.080s). Different request counts and input/output distributions prevent treating differences as causal code gains.</p>')
section('runtime','Runtime and code provenance', '<p>2P ran Prefill PP4 workers on 132/151 and Decode TP8/DP8 across 130/192. The 1P transition removed only Prefill 151; retained workers kept the same pod and container identities. Node 151 was verified at zero GPU memory with no GPU processes at release. After both reruns, the 12-GPU 1P4+D8 deployment remains allocated; requests are fully drained, owned observers stopped, and no further replay is scheduled.</p><p>The only infrastructure placement difference from the historical recipe was moving the 16GiB Mooncake metadata-master reservation from 130 to 192 to pass the RAM preflight. Model-worker placement, pool sizes, images, source overlays and native frontend were retained.</p>'+table(['Component','Recorded setting'],[
 ['SGLang base',code('6d08e28b0c0691899973e3f11bf01fdbdf192a63')],['Dynamo base',code('ff778ed59d00979737e278d228ddbfe32b82c296')],
 ['Prefill','PP4 / TP1; max-running 80; chunk/max-prefill 9216; mem fraction .85; prepared-bootstrap priming; compact DSA logits; startup budget refresh'],
 ['Decode','TP8 / DP8 / EP8; max-running 768; mem fraction .9; EAGLE 3 steps, top-k 1, 4 draft tokens; '+code('--speculative-use-rejection-sampling')],
 ['HiCache','1.5 ratio, direct, page_first_direct, write_through, wait_complete; prefetch batch 384, threads 48, queue 4; PP force flush'],
 ['Frontend','Historical UTF-8 parser overlay; KV router, WSPT 256; shared credit .5; decode admission .93; stream interval 1'],
 ['Code delivery',link('https://git.luchentech.com/maas/sglang/-/issues/5','Summary issue: individual draft PRs and full flags')]])+'<p>The current-dev draft PR ports were CPU-tested during packaging; these GPU reruns use the frozen historical overlays. No claim of GPU validation of those rebased PR branches is made here.</p>')
section('reproduce','Evidence and reproduction','<p>Private retained root: '+code(R)+'. This contains dataset plans, exact payloads, source comparisons, render/values, container identities, logs, metrics, run metadata, raw timing exports and failed attempts. The public pack contains aggregate evidence and analysis code.</p>'+table(['Artifact','Location'],[
 ['Dataset IDs, profile IDs and plan hashes',link('80k-evidence/datasets.json','datasets.json')],
 ['2P raw-derived aggregate audit',link('80k-evidence/run-2p1d-80k.json','2P analysis')],
 ['1P raw-derived aggregate audit',link('80k-evidence/run-1p1d-80k.json','1P analysis') if 'run-1p1d-80k' in results else 'Pending'],
 ['Original source corpus',code('/mnt/HPC/replay/data/traffic_log_20260724_0700-2000_replay_v2')],
 ['Dataset selection / validation',code('finite_plan_80k_chain_lookahead.py; audit_token_prefix_oracle.py; audit_2p_cache.py; audit_2p_tiers.py')],
 ['Request and traffic analysis',code('analyze_run.py; audit_live_rolling.py; audit_live_duration.py; bound_missing_generation_medians.py')],
 ['Source overlays / PR mapping',link('index.html#changes','Main investigation code record')],
 ['Private reproduction capsule',link('80k-evidence/reproduction-capsule.json','234-file verified archive: location, checksum and external prerequisites')],
 ['Changes and milestones',link('80k-evidence/CODE-CHANGE-LEDGER.md','Code/control ledger')+' · '+link('80k-evidence/MILESTONES.md','Milestones')],
 ['Checksum manifest',link('80k-evidence/SHA256SUMS','80K evidence checksums')],
 ['Document generator',link('80k-evidence/build_80k_report.py','build_80k_report.py')]])+'<ol><li>Verify source pack, token profile, candidate hashes and exact original HTTP-body output policy. Re-run the independent prefix oracle and all-boundary capacity/load checks.</li><li>Check current ownership and free resources, then render the retained recipe. Historical names and pod identities must be refreshed before deployment. Model weights, private credentials and pinned images are external prerequisites.</li><li>Verify effective source/native hashes, per-rank capacities and rejection-sampling compatibility. Run retrieval checks, drain and reset only the owned caches; retain the empty-Store receipt.</li><li>Run the separate warmup and require full meaningful-output coverage. Admit the measured 600s workload with its recorded output policy, then allow all original responses to finish. Keep failure/backlog guards and bounded observers active.</li><li>Export immutable raw timing scalars and hash the complete original raw file. Recompute chart cohorts and audit actual arrival-time input/cache traffic. Separate protocol failures, missing generation, generator validity and latency acceptance.</li><li>Close only the owned collectors after terminal accounting and idle checks. Record resource ownership and any released GPUs.</li></ol><p>The request analyzer reproduced all 603 historical ATT56 chart windows and its 23 missing-generation observations before evaluating the new run. Alex report finalization may continue after the last response; the 2P report took about 109s of additional CPU processing. That time is excluded from request latency.</p>')
css='''*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#243548;font:16px/1.65 system-ui,sans-serif}header{padding:28px 42px;background:#fff;border-bottom:1px solid #dbe2e8}h1{margin:8px 0;font-size:32px}header p{color:#586c7f}a{color:#146887}code{font:12px/1.7 ui-monospace,monospace;background:#eef3f6;padding:2px 4px;overflow-wrap:anywhere}.layout{max-width:1450px;margin:26px auto;display:grid;grid-template-columns:215px minmax(0,1120px);gap:28px;padding:0 24px}aside{position:sticky;top:20px;align-self:start;border-left:3px solid #ced9e2;padding:12px}aside a{display:block;padding:7px 0;color:#4d6275;text-decoration:none;font-size:14px}article{min-width:0}section{padding:25px 30px;background:#fff;border:1px solid #dfe5eb;border-radius:8px;margin-bottom:22px;scroll-margin-top:18px}h2{margin:0 0 14px;font-size:25px}h3{font-size:17px}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;padding:10px 12px;border-bottom:1px solid #dfe6eb;vertical-align:top}th{background:#edf2f6}.scroll{overflow:auto}.note{border-left:4px solid #bb732f;background:#fff6e9;padding:14px 18px}select{font:14px system-ui;padding:8px;max-width:100%}.chart{border:1px solid #e0e7ed;border-radius:6px;margin-top:18px;padding:14px}svg{display:block;width:100%;height:auto}#readout{min-height:28px;color:#466477}li{margin:8px 0}footer{color:#657c8e;padding:12px}'''
js='''const data=JSON.parse(document.getElementById('data').textContent),sel=document.getElementById('run-select');function draw(){let pts=data[sel.value].points;for(let[id,c,unit,limit,color,div]of[['ttft',1,'s',4,'#197391',1000],['tpot',2,'ms',40,'#a65b35',1]]){let svg=document.getElementById(id),end=Math.max(...pts.map(p=>p[0])),max=Math.max(limit*1.2,...pts.filter(p=>p[c]!=null).map(p=>p[c]/div))*1.05,X=t=>55+810*t/end,Y=v=>218-190*v/max,s='';for(let i=0;i<=4;i++){let v=max*i/4;s+=`<line x1="55" x2="865" y1="${Y(v)}" y2="${Y(v)}" stroke="#e1e8ed"/><text x="48" y="${Y(v)+4}" text-anchor="end" font-size="11">${v.toFixed(1)}</text>`}for(let t=0;t<=end;t+=120)s+=`<text x="${X(t)}" y="243" text-anchor="middle" font-size="11">${t}s</text>`;s+=`<line x1="55" x2="865" y1="${Y(limit)}" y2="${Y(limit)}" stroke="#b84334" stroke-dasharray="5 4"/><text x="863" y="${Y(limit)-5}" text-anchor="end" font-size="11">${limit} ${unit}</text>`;if(end>600)s+=`<line x1="${X(600)}" x2="${X(600)}" y1="20" y2="218" stroke="#899eaf" stroke-dasharray="3 5"/>`;let pen=false,path=pts.map(p=>{if(p[c]==null){pen=false;return ''}let cmd=pen?'L':'M';pen=true;return cmd+X(p[0])+','+Y(p[c]/div)}).join(' ');s+=`<path class="series" fill="none" stroke="${color}" stroke-width="2" d="${path}"/>`;svg.innerHTML=s;svg.onmousemove=e=>{let b=svg.getBoundingClientRect(),t=((e.clientX-b.left)/b.width*900-55)/810*end,q=pts.reduce((a,b)=>Math.abs(b[0]-t)<Math.abs(a[0]-t)?b:a);document.getElementById('readout').textContent=sel.value+' · '+q[0]+'s · TTFT P50 '+(q[1]==null?'N/A':(q[1]/1000).toFixed(3)+'s')+' · TPOT P99 '+(q[2]==null?'N/A':q[2].toFixed(3)+'ms')+(q[3]==null?'':' · n='+q[3])}}}sel.onchange=draw;draw();'''
nav=''.join(link('#'+i,t) for i,t,c in sections);body=''.join('<section id="'+i+'"><h2>'+esc(t)+'</h2>'+c+'</section>' for i,t,c in sections)
page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GLM-5.3 · 80K request reruns</title><style>'+css+'</style></head><body><header>'+link('index.html','GLM-5.3 investigation')+'<h1>80K input requests: rerunning 2P1D and 1P1D</h1><p>60M/6M and 30M/3M TPM · original Zhipu requests · Updated '+now+'</p></header><div class="layout"><aside aria-label="Contents">'+nav+'</aside><article>'+body+'<footer>All wall times are Singapore time. Failed gates and workload limitations remain part of the evidence.</footer></article></div><script type="application/json" id="data">'+json.dumps(charts).replace('</','<\\/')+'</script><script>'+js+'</script></body></html>'
(O/'80k-reruns.html').write_text(page)
for name in ['CODE-CHANGE-LEDGER.md','MILESTONES.md','summarize_output_distribution.py','analyze_run.py','audit_live_rolling.py','audit_live_duration.py','bound_missing_generation_medians.py','audit_token_prefix_oracle.py','finite_plan_80k_chain_lookahead.py','audit_2p_cache.py','audit_2p_tiers.py']:
 shutil.copy2(R/name,E/name)
shutil.copy2(Path(__file__),E/'build_80k_report.py')
(E/'SHA256SUMS').write_text(''.join(hashlib.sha256(p.read_bytes()).hexdigest()+'  '+p.name+'\n' for p in sorted(E.iterdir()) if p.is_file() and p.name!='SHA256SUMS'))
print(json.dumps({'page':str(O/'80k-reruns.html'),'completed_arms':list(results),'charts':list(charts),'bytes':len(page)}))
