"""Build a portable public investigation record from explicit, non-secret evidence."""
from pathlib import Path
import datetime
import hashlib
import html
import json
import re
import shutil

ROOT=Path(__file__).resolve().parents[1]
OLD=Path('/mnt/HPC/tom/pd-queue-overnight-20260912.twotxxas')
OUT=Path('/home/tom/maas_docs/docs/glm53-gb300-ttft-tpot-optimization')
OUT.mkdir(parents=True,exist_ok=True)
esc=html.escape
data=json.loads((ROOT/'evidence/latency-comparison.json').read_text())
published={**data,'runs':[{k:v for k,v in r.items() if k!='worst_requests'} for r in data['runs']]}
(OUT/'latency-comparison.json').write_text(json.dumps(published,indent=2)+'\n')
candidate=OLD/'candidates/same-iteration-map-copy'
for name in ['cumulative-against-frozen.patch','cumulative-patch-check.json','lifetime-results.json','negative-controls.json','ordering-results.json','source-scope-results.json']:
    shutil.copyfile(candidate/name,OUT/name)
shutil.copyfile(ROOT/'worker/analyze_latency.py',OUT/'analyze_latency.py')
shutil.copyfile(ROOT/'worker/decompose_spike_traces.py',OUT/'decompose_spike_traces.py')
shutil.copyfile(ROOT/'worker/analyze_output_profiles.py',OUT/'analyze_output_profiles.py')
trace_data=json.loads((ROOT/'evidence/spike-traces/decomposition.json').read_text())
(OUT/'trace-cohort-summary.json').write_text(json.dumps(trace_data['summary'],indent=2)+'\n')
for rid,suffix,name in [('20260913_023856','','diagnostic-att21.json'),('20260913_030350','-partial','negative-att22.json')]:
    follow=json.loads((ROOT/'evidence'/('latency-comparison-'+rid+suffix+'.json')).read_text())
    follow['runs']=[{k:v for k,v in row.items() if k!='worst_requests'} for row in follow['runs']]
    (OUT/name).write_text(json.dumps(follow,indent=2)+'\n')
shutil.copyfile(ROOT/'attempt22-prefill6k/rollout/trial-values.json',OUT/'prefill6k-values.json')
shutil.copyfile(ROOT/'attempt25-pd-only-kv-fingerprint/evidence/FINDINGS.json',OUT/'kv-boundary-att25.json')
shutil.copyfile(ROOT/'candidates/dsa-snapshot-layout/diagnostic-layout.patch',OUT/'diagnostic-fingerprint.patch')
shutil.copyfile(ROOT/'attempt26-nonfinal-forward-fence/evidence/FINDINGS.json',OUT/'producer-fence-att26.json')
shutil.copyfile(ROOT/'attempt27-async-kv-event/evidence/FINDINGS.json',OUT/'producer-event-att27.json')
shutil.copyfile(ROOT/'candidates/pp-async-kv-event/async-kv-event.patch',OUT/'async-kv-event.patch')
shutil.copyfile(ROOT/'candidates/pp-async-kv-event/CPU-RESULT.json',OUT/'async-kv-event-cpu.json')
shutil.copyfile(ROOT/'expanded-four-node/dataset/SUMMARY.json',OUT/'doubled-load-candidate-summary.json')
shutil.copyfile(ROOT/'candidates/optimized-async-kv-event/event-on-six-patches.patch',OUT/'optimized-event.patch')
att28=json.loads((ROOT/'evidence/latency-comparison-20260913_050451.json').read_text())
att28['runs']=[{k:v for k,v in row.items() if k!='worst_requests'} for row in att28['runs']]
(OUT/'latency-att28.json').write_text(json.dumps(att28,indent=2)+'\n')
shutil.copyfile(ROOT/'attempt28-lane-b-optimized-event/REPORT.md',OUT/'att28-report.md')
shutil.copyfile(ROOT/'expanded-four-node/two-prefill-one-decode/REPORT.md',OUT/'two-prefill-one-decode-report.md')
partial=json.loads((ROOT/'expanded-four-node/two-prefill-one-decode/replay/partial-analysis.json').read_text())
partial.pop('worst_deficits',None)
(OUT/'two-prefill-partial-summary.json').write_text(json.dumps(partial,indent=2)+'\n')
shutil.copyfile(ROOT/'attempt30-two-prefill-12k/REPORT.md',OUT/'att30-report.md')
att30=json.loads((ROOT/'evidence/latency-comparison-20260913_063354-partial.json').read_text())
att30['runs']=[{k:v for k,v in row.items() if k!='worst_requests'} for row in att30['runs']]
(OUT/'latency-att30.json').write_text(json.dumps(att30,indent=2)+'\n')
partial30=json.loads((ROOT/'attempt30-two-prefill-12k/replay/partial-analysis.json').read_text())
partial30.pop('worst_deficits',None)
(OUT/'att30-partial-summary.json').write_text(json.dumps(partial30,indent=2)+'\n')
shutil.copyfile(ROOT/'expanded-four-node/dataset/workload-mix-comparison.json',OUT/'workload-mix-comparison.json')
shutil.copyfile(ROOT/'expanded-four-node/two-prefill-stage-comparison.json',OUT/'two-prefill-stage-comparison.json')
shutil.copyfile(ROOT/'attempt31-two-prefill-matched-rate/REPORT.md',OUT/'att31-report.md')
att31=json.loads((ROOT/'evidence/latency-comparison-20260913_070704-partial.json').read_text())
att31['runs']=[{k:v for k,v in row.items() if k!='worst_requests'} for row in att31['runs']]
(OUT/'latency-att31.json').write_text(json.dumps(att31,indent=2)+'\n')
work31=json.loads((ROOT/'attempt31-two-prefill-matched-rate/replay/workload-analysis.json').read_text());work31.pop('worst_deficits',None)
(OUT/'att31-workload-summary.json').write_text(json.dumps(work31,indent=2)+'\n')
shutil.copyfile(ROOT/'expanded-four-node/request-rate-control-stages-120s.json',OUT/'request-rate-control-stages.json')
shutil.copyfile(ROOT/'expanded-four-node/request-rate-control-cache-tiers-60s.json',OUT/'request-rate-control-cache-tiers.json')
shutil.copyfile(ROOT/'attempt32-two-prefill-session-affinity/REPORT.md',OUT/'att32-report.md')
att32=json.loads((ROOT/'evidence/latency-comparison-20260913_073337-partial.json').read_text())
att32['runs']=[{k:v for k,v in row.items() if k!='worst_requests'} for row in att32['runs']]
(OUT/'latency-att32.json').write_text(json.dumps(att32,indent=2)+'\n')
work32=json.loads((ROOT/'attempt32-two-prefill-session-affinity/replay/workload-analysis.json').read_text());work32.pop('worst_deficits',None)
(OUT/'att32-workload-summary.json').write_text(json.dumps(work32,indent=2)+'\n')
shutil.copyfile(ROOT/'attempt32-two-prefill-session-affinity/evidence/stage-cache-comparison.json',OUT/'affinity-stage-cache-comparison.json')
A33=ROOT/'attempt33-two-prefill-strict-affinity'
shutil.copyfile(A33/'REPORT.md',OUT/'att33-report.md')
att33=json.loads((ROOT/'evidence/latency-comparison-20260913_075613.json').read_text())
att33['runs']=[{k:v for k,v in row.items() if k!='worst_requests'} for row in att33['runs']]
(OUT/'latency-att33.json').write_text(json.dumps(att33,indent=2)+'\n')
work33=json.loads((A33/'replay/workload-analysis.json').read_text());work33.pop('worst_deficits',None)
(OUT/'att33-workload-summary.json').write_text(json.dumps(work33,indent=2)+'\n')
shutil.copyfile(A33/'evidence/affinity-stage-cache-600s.json',OUT/'strict-affinity-stage-cache.json')
shutil.copyfile(A33/'replay/evidence/store-counter-deltas.json',OUT/'strict-affinity-store-deltas.json')
trace33=json.loads((A33/'spike-traces/decomposition.json').read_text())
(OUT/'strict-affinity-trace-summary.json').write_text(json.dumps(trace33['summary'],indent=2)+'\n')
for name in ['complete-against-frozen.patch','complete-patch-verification.json']:
    shutil.copyfile(ROOT/'candidates/optimized-async-kv-event'/name,OUT/name)
for name in ['MILESTONES.md','CODE-CHANGE-LEDGER.md']:
    shutil.copyfile(ROOT/name,OUT/name.lower())
snapshot=json.loads((ROOT/'milestones/attempt33-two-prefill-strict-affinity/VERIFIED.json').read_text())
(OUT/'att33-snapshot-verification.json').write_text(json.dumps(snapshot,indent=2)+'\n')
A34=ROOT/'attempt34-two-prefill-12k-strict-affinity'
shutil.copyfile(A34/'REPORT.md',OUT/'att34-report.md')
att34=json.loads((ROOT/'evidence/latency-comparison-20260913_084212.json').read_text())
att34['run_state']='invalid_load_generator'
att34['runs']=[{k:v for k,v in row.items() if k!='worst_requests'} for row in att34['runs']]
(OUT/'latency-att34.json').write_text(json.dumps(att34,indent=2)+'\n')
work34=json.loads((A34/'replay/workload-analysis.json').read_text());work34.pop('worst_deficits',None)
(OUT/'att34-workload-summary.json').write_text(json.dumps(work34,indent=2)+'\n')
for source,name in [('replay/rolling-load-cache-audit.json','att34-rolling-load-cache.json'),('replay/evidence/store-counter-deltas.json','att34-store-deltas.json'),('evidence/affinity-stage-cache-600s.json','att34-stage-cache.json')]:
    shutil.copyfile(A34/source,OUT/name)
shutil.copyfile(ROOT/'milestones/attempt34-two-prefill-12k-strict-affinity/VERIFIED.json',OUT/'att34-snapshot-verification.json')
shutil.copyfile(OLD/'evidence/map-copy-replication.json',OUT/'replication.json')
shutil.copyfile(Path(__file__),OUT/'build_report.py')
sha={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in OUT.iterdir() if p.is_file() and p.name not in ['index.html','SHA256SUMS']}
(OUT/'SHA256SUMS').write_text(''.join(f'{v}  {k}\n' for k,v in sorted(sha.items())))
sections=[]
def section(id,title,body):sections.append((id,title,body))
def table(headers,rows):
    return '<div class="table-scroll"><table><thead><tr>'+''.join('<th>'+esc(str(h))+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def code(x):return '<code>'+esc(str(x))+'</code>'
def reportlink(rid):return '<a href="http://43.156.43.133:31019/replay/runs/'+rid+'/report?view=overview&amp;columns=overview">'+rid+'</a>'
section('status','Current primary goal: doubled-traffic TTFT','''<div class="callout"><strong>Make 2P1D meet the strict TTFT standard achieved in 1P1D.</strong> Every Alex trailing 20-second completion-window p50 must remain below 4 seconds throughout the full ten-minute test, at approximately 60M input / 6M uncached TPM, with zero request failures. At 16:22 Singapore, Tom deprioritized standalone TPOT-spike and further KV-correctness research unless they block this goal. Keep the producer-event fix and bounded regression checks.</div>
<p>ATT34 completed all 11,842 requests with zero failures and empty outputs, but Alex marked its generator invalid: event-loop lag p99 was 50.39ms, above the existing 50 ms limit. Its observed TTFT improved, yet56 of 603 windows still exceeded 4 seconds. ATT35 repeats the unchanged 12K configuration with fresh cache and the same validation limits. ATT33 remains the latest full run with a valid generator; it also failed the TTFT window target.</p>'''+table(['Finished run','Input / uncached TPM','Global TTFT p50 / p99','Worst Alex20s p50','Outcome'],[
[reportlink('20260913_084212'),'60.033M / approximately6.078M','3.345 / 5.804 s','4.571 s','ATT34: generator invalid; diagnostic only;56/603 TTFT windows fail'],
[reportlink('20260913_075613'),'60.033M / approximately 6.069M','3.773 / 6.920 s','6.116 s','2P1D: zero errors; TTFT windows fail'],
[reportlink('20260913_050451'),'30.0255M / 2.9970M','2.248 / 3.626 s','3.064 s','1P1D: all 602 TTFT windows pass; zero errors'],
])+'''<p>The best 1P1D run is preserved; its test lanes are stopped and its nodes now participate in 2P1D. Its TPOT tails remain open. <a href="att28-report.md">1P1D record</a> · <a href="att33-report.md">2P1D with valid generator record</a> · <a href="att34-report.md">ATT34 diagnostic record and invalidity</a>.</p>''')
section('chunk-repeat','ATT34: 12K tradeoff; unchanged repeat required','''<div class="callout"><strong>Generator invalid; this is not an accepted performance result.</strong> Event-loop lag p99 was 50.389651 ms against the unchanged 50 ms ceiling. Admission p99 37.373ms and body-send p99 47.117ms passed their separate limits; connector queue events were zero. All 11,842 requests succeeded, and all 115 queue gauges drained.</div>
<p>Only both Prefills changed from 8K to 12K chunks/max-prefill limits, adding the matching CUDA-graph size on every PP rank. Six other pod/container incarnations, all source patches, images, affinity 1800s / escape 0, eight-GPU Decode,1300 GiB Store and candidate05 workload remained fixed. No image was rebuilt and no serving code was added.</p>'''+table(['ATT34 observation','Result'],[
['TTFT p50 / p90 / p99','3.345 / 4.565 / 5.804 s'],['Worst 20s p50 / failing windows','4.571 s at t=457; 56/603 above 4s'],['ATT33 reference','6.116 s worst; 213/603 above 4s; valid generator'],['Measured cache hit / uncached tokens','89.875018% / 60,783,648'],['Full 60s demand windows','42,621 boundary/interior states; all within recorded engineering bands'],['Actual uncached 60s range','5,935,560–6,291,694 tokens'],['Store eviction churn','47 passes; 2.959 TB cumulative evicted bytes'],['Warmup, separately recorded','400/400 success; cold-cache TTFT p50 16.931s'],
])+'''<p>Raw timings reproduce every one of the 603 chart points. Early Prefill queues were smaller with 12K, while per-request forward, bootstrap and handoff counter means grew. This tradeoff motivates further work, but a valid unchanged repeat is needed before attributing the difference confidently. The 52 lower-tier-index warnings and deferred TPOT tails remain in the private evidence; an absent-block removal warning alone does not prove lost KV data.</p>
<p><strong>ATT35 repeats the exact 12K serving configuration.</strong> All eight runtime incarnations are retained. Fresh generator/token/payload attestation and cache reset precede the same 400-request warmup and 600-second measured schedule. Existing bounded-check results are explicitly inherited from the identical runtime; no new correctness coverage is claimed. Validation thresholds remain unchanged.</p><p>'''+reportlink('20260913_084212')+''' · <a href="att34-report.md">Full result and recipe</a> · <a href="latency-att34.json">Raw chart reconstruction</a> · <a href="att34-workload-summary.json">All-request accounting</a> · <a href="att34-rolling-load-cache.json">Rolling demand audit</a> · <a href="att34-stage-cache.json">Stage/cache counters</a> · <a href="att34-store-deltas.json">Store churn</a> · <a href="att34-snapshot-verification.json">Verified 156-file archive</a>.</p>''')
section('strict-affinity','ATT33: full load completed, Prefill queues remain','''<p>Two PP4/TP1 Prefills run on nodes 132 and 151. One TP8/DP8/EP8 Decode spans nodes 130 and 192; these are two physical pods of one distributed worker. Two 650 GiB Mooncake clients supply a private 1300 GiB shared cache. ATT33 retained 8K Prefill chunks and changed only frontend projected-load escape from 8000 ms to zero, with session affinity at 1800 seconds. Hard admission limits and external failure/backlog guards remained.</p>'''+table(['ATT33 measurement','Result'],[
['Admission / completion span','599.965 / 603.591 s'],['Successful requests / failures / empty outputs','11,842 / 0 / 0'],['Server input / cached / uncached tokens','600,333,408 / 539,642,176 / 60,691,232'],['Actual cache hit / finite-plan net deficit','89.890412% / 686,848 tokens'],['TTFT p50 / p90 / p99','3.773 / 5.247 / 6.920 s'],['Worst Alex20s TTFT p50','6.116 s at t=508; 395 samples'],['Windows above 4s p50','213 / 603; independently reconstructed'],['Load generator / terminal state','Valid; 115 idle gauges; all eight pod/container identities unchanged'],
])+'''<p><strong>Prefill queueing is the leading TTFT target.</strong> In 16 traces from the worst window, mean Prefill waiting was 3.647 s versus 0.571 s in eight control traces. Mean Prefill forward was 0.836 versus 0.776 s. These selected cohorts locate the delay; they are not a randomized causal estimate. Decode transfer-wait overlaps Prefill work and must not be added to those spans.</p>
<p><strong>L3 remains part of the investigation.</strong> Session affinity reduced host/shared-cache movement compared with ATT31, but the finite cache still churned. From the measured baseline to terminal idle, Store recorded 47 eviction passes and 2.958 TB of cumulative evicted bytes; cumulative eviction is not unique working-set size. Allocated bytes ended at 1.206 TB of 1.396 TB capacity. Keep actual GPU/host/L3 hits and misses distinct from the optimistic offline prefix model.</p>
<p>TPOT evidence is retained at lower priority: whole p99 19.616 ms, worst 20s p99 152.274 ms. The 24 sampled worst requests averaged 0.258 s in Decode forward and 2.270 s from scheduler completion to root-request completion. The exact later cause remains unproven. No new CPU profiling or correctness-research overlay was introduced.</p>
<p>Six canonical retrievals and four affinity checks passed before the fresh 400-request warmup. The exact candidate05 replay, source hashes, scoped cache resets, rollback and all negative outcomes remain saved. ATT34 changes only the two Prefills' chunk/max-prefill limits to 12288 and adds the matching graph size, to test throughput headroom.</p><p>'''+reportlink('20260913_075613')+''' · <a href="att33-report.md">Full reproduction record</a> · <a href="att33-workload-summary.json">Load/cache accounting</a> · <a href="latency-att33.json">Reconstructed latency</a> · <a href="strict-affinity-stage-cache.json">Stage/cache counters</a> · <a href="strict-affinity-store-deltas.json">Store churn</a> · <a href="strict-affinity-trace-summary.json">Trace-cohort summary</a>.</p>''')
section('workload','Historical 1P1D workload and configuration',table(['Item','Recorded setting'],[
['Nodes / allocation','ATT19/20: Prefill132 / Decode130; ATT28: Prefill151 / Decode192. Four GB300 GPUs per worker node.'],
['Model','zai-org/glm-5.3; NVFP4 weights; FP8 e4m3 KV'],
['Prefill','PP4 / TP1 / DP1; async depth 1; maximum running 80'],
['Prefill scheduling','8,192-token chunks and max-prefill; breakable CUDA graphs at 512, 1024, 2048, 4096, 8192'],
['Prefill memory','Memory fraction 0.85; 64-token pages; observed GPU KV capacity 9,252,096 tokens per rank'],
['Decode','TP4 / DP4 / PP1; maximum running 384; memory fraction 0.9'],
['Decode speculation','Pre-existing EAGLE; 3 steps; top-k 1; 4 draft tokens; speculative attention mode decode. Prefill has no speculative-algorithm flag.'],
['HiCache / transport','Ratio 1.5; direct; '+code('page_first_direct')+'; '+code('write_through')+'; private Mooncake'],
['Dataset',code('tom-capacity-aware-v2-30m-3m-10min-20260911')],
['Dataset / token profile IDs',code('dataset-22913a80631e1384c956d887')+' / '+code('profile-bed998021231ed619ee5ec5c')],
['Measured replay','600 seconds; 5,921 requests; maximum concurrency 1024; replay speed 1; output cap 20; timeout 120 seconds'],
['Warmup','Separate 100-request / 120-second warmup, maximum concurrency 128, after scoped cache reset'],
['Identity semantics','Session header enabled; unique prefix disabled; cache probe disabled; original source prompts retained'],
['Measured tokens','300,255,283 input; 270,284,992 cached; 29,970,291 uncached in each final run'],
['Offered / useful input','30.0255283M input TPM and 2.9970291M useful uncached TPM over the admission interval; full completion-span uncached TPM 2.9865M / 2.9874M'],
])+'''<p>The 20-token output cap predates this optimization investigation. Short output and stream coalescing limit extrapolation of these TPOT results to long generations. The input requests replay recorded history; generated outputs do not become later request inputs.</p>''')
section('changes','Six retained code changes',table(['Change','Mechanism','Observed evidence'],[
['Earlier control publication','Publish the entire ordered request/bootstrap/release bundle before chunk maintenance.','Removes dependency-independent publication delay; not a standalone solution.'],
['Forward before old-output processing','Launch the next explicit independent Prefill input before processing prior outputs; guard mixed/dependent modes.','Depth 1 is retained while launch order changes; depth 0 alone regressed.'],
['Earlier prior-output publication','Publish ready prior outputs before current activation receive. Initially last rank, later extended across ranks.','Largest observed step: global p50 10.553 → 4.405 s. All-rank extension alone did not show a gain.'],
['Earlier cached-prefix KV send','Transfer already resident prefix KV before waiting for suffix activations.','Observed global p50 4.405 → 3.153 s. Existing cursor and fallback path retained.'],
['Final page-map reuse','Reuse an already gathered final DSA page-map suffix instead of copying it twice.','No demonstrated standalone latency improvement.'],
['Same-iteration non-final map overlap','Enqueue an owned page-index gather and pinned CPU copy, prepare/launch independent work, then join and publish before cleanup.','ATT19 was the first 60-second-window pass; same-code ATT20 replicated it.'],
])+'''<p>Counted by final behavior, there are six optimizations across <code>scheduler_pp_mixin.py</code> and <code>prefill.py</code>. The cumulative diff has 351 insertions and 74 deletions; line counts include guards and moved/indented code. Development preserved 12 source variants: ten performance candidates and two timing-instrumentation variants. This is not a count of commits or experiments.</p>
<p>The small page map identifies where KV pages live; this optimization does not copy the bulk KV cache into host memory. It preserves the page-map copy dependency and owns scratch/pinned buffers until completion, validates request/sender/row generation and cursors, and flushes or cancels before result handling, release, or a subsequent loop iteration. Alternate allocators, transports and unsupported modes retain the original path. Subsequent ATT25–27 work identified a separate bulk-KV producer dependency gap; the old page-map wait alone does not fence those bytes. ATT28 combines both producer-event paths with these six optimizations.</p>
<p><a href="cumulative-against-frozen.patch">Download the complete optimization patch</a> · <a href="cumulative-patch-check.json">Exact reconstruction check</a> · <a href="SHA256SUMS">Artifact checksums</a>. The main SGLang branch was not modified or merged; tests used Helm-owned source overlays. Other pre-existing runtime overlays remain required dependencies.</p>''')
section('measurement','Definitions and corrected acceptance scope','''<p><strong>Primary user latency:</strong> raw client TTFT runs from completed request-body upload to first meaningful generation event. Upload, connection setup, usage-only messages and DONE are excluded. Frontend and SGLang timers start and stop at different boundaries; coarse Grafana histogram percentiles must not be substituted for raw client percentiles.</p>
<p><strong>Alex chart:</strong> trailing 20-second windows, grouped by protocol completion time, evaluated every second; sparse windows with fewer than three samples are null. Percentiles use linear interpolation. The follow-up independently rebuilt every saved chart point for all 15 uninstrumented runs, including the preceding baseline.</p>
<p><strong>Earlier acceptance:</strong> 60-second windows grouped by request arrival, with latency followed to completion. ATT19 and ATT20 each passed 21,240 checked boundaries. This remains a valid narrow result, but does not imply the shorter chart windows pass.</p>
<div class="equation"><span>TPOT</span><span>=</span><span>1,000 × (last generation time − first generation time) / (output tokens − 1)</span><span class="unit">ms/token</span></div>
<p>The TPOT distribution is across successful requests with more than one output token. It is not the distribution of every individual inter-token gap. Multiple tokens can share one observed stream-event timestamp. About 46% of requests in these short-output trials have zero observed first-to-last span; that is coalescing at the client boundary, not infinite physical decode speed.</p>
<p>Cross-run changes below are observational, not randomized or counterbalanced causal estimates. Baseline failures also change the successful-request population. The historical 1P1D final runs match all 5,921 request identities and input/cache counts; the newer 2P1D arms use the separately verified 11,842-request candidate05.</p>''')
chart_data={r['run_id']:{'label':r['arm'],'points':[[p['t'],p['ttft']['p50'],p['tpot']['p99']] for p in json.loads((ROOT/'evidence'/r['run_id']/'timeseries.json').read_text())['distribution_sliding']['points']]} for r in data['runs']}
for rid,label in [('20260913_084212','ATT34 12K: GENERATOR INVALID;11842success/0failure;diagnostic only'),('20260913_075613','ATT33 2P1D strict affinity: complete;11842success/0failure'),('20260913_073337','ATT32 affinity: interrupted;956success/14HTTP400'),('20260913_070704','ATT31 matched request rate: interrupted;2968success/0failure'),('20260913_063354','ATT30 2P1D 12K: interrupted;3942success/12failure'),('20260913_055201','ATT29 2P1D: interrupted negative trial,4705admitted'),('20260913_050451','ATT28 optimized event: strictTTFTpass, TPOTopen'),('20260913_023856','ATT21 CPU diagnostic'),('20260913_030350','ATT22 6K: interrupted negative trial; 3289 admitted')]:
    chart_data[rid]={'label':label,'points':[[p['t'],p['ttft']['p50'],p['tpot']['p99']] for p in json.loads((ROOT/'evidence'/rid/'timeseries.json').read_text())['distribution_sliding']['points']]}
section('curves','Inspect the short-window spikes','''<p>Select a run to inspect the same saved 20-second completion windows used by Alex. Hover over a plot for the nearest sample. These figures preserve the spikes.</p><label>Run <select id="run-select">'''+''.join('<option value="'+rid+'"'+(' selected' if rid=='20260913_084212' else '')+'>'+esc(rid+' · '+r['label'].replace('_',' '))+'</option>' for rid,r in chart_data.items())+'''</select></label><div class="chart-card"><h3>TTFT p50 · seconds</h3><svg id="ttft-chart" viewBox="0 0 900 250" role="img" aria-label="TTFT p50 over elapsed seconds"></svg></div><div class="chart-card"><h3>TPOT p99 · milliseconds</h3><svg id="tpot-chart" viewBox="0 0 900 250" role="img" aria-label="TPOT p99 over elapsed seconds"></svg></div><p id="point-readout" aria-live="polite">Elapsed seconds from first measured request-body send.</p>''')
section('tpot','TPOT stall evidence and regression question','''<p>The repeat has ten requests above 40 ms TPOT and four above 80 ms. Its whole-run p99 is 17.236 ms, but the worst 20-second p99 is 83.391 ms. A small cluster of stalled streams can therefore dominate a short-window p99 without changing the whole-run p99 much.</p>
<p>At approximately 350.937–352.463 elapsed seconds, four active streams share a 1.526-second gap in all observed token receipts. Sixteen new requests are dispatched during that gap. This argues against a complete freeze of the load-generator event loop. The exact trace joins below further localize the delay.</p>
<p><strong>The stall pattern existed before the retained source patches:</strong> the depth-2 baseline already had three individual TPOT values above 80 ms; the depth-1 configuration-only trial had a 90.31 ms short-window p99. This disproves that the final map-copy patch first introduced the phenomenon. It does not establish that the patches have zero effect on its frequency or clustering.</p>
<p>Whole-run TPOT p99 improved from 21.39 ms in the original depth-2 baseline to 17.34 / 17.24 ms in the final runs. Exact joins recovered 37 traces / 1,998 spans. The ten TPOT-tail requests have Decode-forward durations of 0.189–0.334 seconds. Every enclosing Decode request ends 1.022–1.460 seconds after its Decode Scheduler span ends, measured within the same SGLang service. This avoids relying on client/server clock alignment for that gap. The evidence localizes much of the stall after Decode scheduling, in output handling/delivery; it does not yet identify the blocking function.</p>
<p>The TTFT-hot cohort instead has mean Prefill waiting of 2.091 seconds, versus 0.098 seconds in a nearby control cohort. At the worst TTFT chart point, TPOT p99 is only 16.56 ms. At the worst TPOT point, TTFT p50 is 2.995 seconds. The two spike mechanisms should be investigated separately. Both final runs have identical 20-second arrival-window uncached-load ranges of approximately 2.794–3.172M TPM, which weakens a large offered-load burst as the explanation.</p>
<p><a href="trace-cohort-summary.json">Trace cohort summary</a> · <a href="decompose_spike_traces.py">Reproduction script</a>. Exact request/span identifiers remain in the private trace evidence directory. Python garbage collection remains one candidate mechanism, not an established cause.</p>''')
section('followup','Follow-up diagnostic and next controlled trial','''<p>ATT21, '''+reportlink('20260913_023856')+''', completed after an unchanged-runtime 100-request warmup. All 5,921 requests succeeded with complete TTFT, output and DONE; identities and input/cache counts matched ATT20. The generator was valid, all 22 observed error/rejection series had zero increments, 56 queue gauges were idle twice, and all three original containers remained Ready with zero restarts. Its collectors are closed.</p>'''+table(['ATT21 diagnostic metric','Result'],[['Global TTFT p50 / p99','2.533 / 4.554 seconds'],['Worst 20s completion TTFT p50','4.299 seconds at 444s; 163 requests; 28 chart points above 4s'],['Global / worst 20s TPOT p99','17.394 / 52.658 ms'],['Individual TPOT tails','7 requests above 40ms; 3 above 80ms'],['CPU capture','Two nonblocking 10Hz recordings lasting 660s; Decode Python PID 1 and detokenizer PID 366'],['Capture quality','PID 1: 33,064 thread samples / 130 read errors; PID 366: 19,683 thread samples / 38 errors']])+'''<p>This is diagnostic evidence, not an uninstrumented performance acceptance run. Most main-thread samples ended at the native event-loop boundary; detokenizer samples mostly waited for input. The capture did not isolate a long Python loop. Native stacks were absent, and failed reads plus synthetic sample weights prevent exact wall-time attribution. No explicit GC sample does not rule out garbage collection.</p>
<p>The sampled serving path is the older Dynamo <code>request_handlers/llm/decode_handler.py</code>, not the colocated newer <code>llm_engine.py</code>. Active handler/main source files and hashes were preserved. Any startup-freeze proposal must be based on the active initialization path. <a href="analyze_output_profiles.py">CPU-sample analysis script</a>; private profiles are in <code>attempt21-output-delivery-diagnostic/cpu-stacks/</code>.</p>
<p><strong>ATT22 is a failed, interrupted trial:</strong> '''+reportlink('20260913_030350')+'''. Prefill scheduling size changed from 8,192 to 6,144 tokens with a matching graph bucket. Exact source, images, memory/cache settings, depth 1, output cap 20 and workload remained fixed. The initial recent p50 was about 1.8 seconds, but sustained Prefill backlog developed. Admissions stopped at 341.732 seconds. Of 3,289 admitted requests, 3,276 succeeded and 13 received HTTP 529 overload responses; 2,632 planned requests were intentionally not admitted.</p>'''+table(['ATT22 interrupted trial','Observed result'],[['Successful-request TTFT p50 / p99','4.627 / 17.139 seconds'],['Worst 20s completion TTFT p50','16.818 seconds at 357s; 202 samples; 218 chart points above 4s'],['Global / worst 20s TPOT p99','17.380 / 56.393 ms'],['Load generator','Valid; all admitted client outcomes accounted for'],['Residual serving state','13 pending Prefill bootstraps per PP rank after client completion; Decode and frontend client gauges idle'],['Recovery','Exact saved 8K recipe restored and Ready; retrieval correctness anomaly under investigation']])+'''<p>The 6K configuration did not sustain enough Prefill throughput at the fixed offered load. The frontend rejection/error counters increased by 13; sampled backend rejection counters did not increase. Residual Prefill bootstraps are consistent with the previously reported cleanup bug after overload. No cleanup fix is claimed.</p>
<p>The old drain watcher and all collectors were closed before recovery. The record explicitly distinguishes complete client drain from incomplete engine drain; the replacement worker cannot retroactively make the failed trial appear drained. The recovery diff restores only the three Prefill argument values. An initial preflight stopped before mutation because the default Kubernetes API schema differed from the chart schema; the corrected check reads the explicit API conversion.</p>
<p><a href="diagnostic-att21.json">ATT21 aggregate evidence</a> · <a href="negative-att22.json">ATT22 partial-run evidence</a> · <a href="prefill6k-values.json">Exact 6K values override</a>. The interrupted trial is excluded from the full-run comparison table. Its truncated percentiles are not directly comparable to complete ten-minute trials. Since the TPOT stall pattern predates the retained source patches, its unresolved root cause can take lower priority while testing the remaining TTFT spikes.</p>''')
section('recovery-correctness','Historical retrieval anomaly and follow-up','''<div class="callout"><strong>This historical anomaly paused performance tuning.</strong> Later ATT25–27 isolated and fenced a bulk-KV producer dependency; the event-fenced candidate subsequently passed bounded retrieval checks. After restoring the exact 8K configuration, the third synthetic retrieval probe generated repeated digits, reached its 256-token limit and produced no final answer. The first two probes returned the expected identifiers. This is preserved as a failed correctness check, not discarded as a short-budget test.</div>
<p>The worker is Ready with unchanged source/image hashes, fixed KV capacity and all four 8K graph captures. A fresh-cache repeat returned all three correct identifiers; its exact-text comparison differed only in whitespace. A later pass does not explain or erase the first failure. A predeclared five-trio series then passed all 15 requests after owned-cache resets, with exact input/cache coverage. These later passes do not establish the original cause. A source control restored both Prefill files to their exact frozen pre-optimization versions, keeping the 8K settings, other overlays, images and Decode/frontend containers fixed. Its predeclared series returned 14 correct answers out of 15. The first third-cold probe stopped after only one identifier, although all protocol completions and input/cache counts were correct; the following 12 requests passed. All four native 8K graphs executed. The retained patches are therefore not necessary for this fixture to exhibit a retrieval failure. The two observed failure modes differ, and these small series do not establish the exact cause or prove zero patch effect.</p>
<p>Private evidence: <code>/mnt/HPC/tom/pd-latency-followup-20260913/recovery-after-att22/retrieval-candidate.json</code>, <code>retrieval-repeat01-candidate.json</code>, and <code>retrieval-series-retained8k/</code>. The frozen control and all logs are under <code>attempt23-frozen-source-correctness/</code>. Existing successful latency runs remain valid observations of speed, but do not constitute comprehensive answer-correctness validation. Further research is now deprioritized unless it blocks the primary 2P1D goal; no full load run has been started on the frozen control.</p>''')
section('session-affinity','Session affinity: better early locality, routing failures','''<div class="callout"><strong>ATT32 is a failed, interrupted test.</strong> Of 970 admitted requests, 956 succeeded and 14 received HTTP 400 session-binding errors. The remaining 10,872 requests were never admitted. All 51 reconstructed successful-request Alex windows stayed below 4s, but errors and the short duration prevent a performance pass.</div>
<p>Only frontend session affinity changed, to 1,800 seconds. Candidate05, two 8K Prefills on 132/151, the one eight-GPU Decode on 130/192, two 650 GiB shared-cache clients, images, source overlays and admission limits remained fixed. Six canonical retrieval checks and four unforced continuation-routing probes passed before measurement; all 400 warmup requests succeeded.</p>'''+table(['ATT32 interrupted result','Observed'],[['Last body send / last completion','48.627 / 51.390 s'],['Successful whole TTFT p50 / p99','2.268 / 3.444 s'],['Worst successful Alex20 s TTFT p50','2.573 s; zero chart points above 4 s'],['Whole / worst Alex20 s TPOT p99','19.397 / 20.062 ms'],['Successful cache hit / net deficit','89.9977% / 960 tokens'],['Errors','14 HTTP 400, all bound to P151 but selected P132'],['Recovery','14 bootstrap entries timed out after 300 s; 115 gauges idle without restarting']])+'''<p><strong>Locality improved before the failures.</strong> In approximately the first 30 s, combined host/shared-cache hit tokens fell from 908,928 in ATT31 to 196,736. In the following approximately ten seconds they fell from 2,302,592 to 121,472; mean Prefill queue times on 132/151 were 1,070/1,564 ms versus 521/452 ms. Actual scrape offsets and all counter sums are retained. These are observation-time cohorts, not an additive request-latency decomposition.</p>
<p><strong>The failure is consistent with conflicting routing rules.</strong> The frozen selector code may drop a worker pin when modeled Prefill backlog exceeds 8,000 ms and another worker is projected to free sooner. The affinity coordinator then validates the selected worker against the session binding after dispatch. All fourteen client failures have that exact native error form. Their preceding measured session requests had already completed, so this is not evidence of a first-request concurrency race. Exact compiled Rust source provenance and debug escape logs are incomplete; the configuration control must test this explanation.</p>
<p>Every failed client was joined to exactly one PP0 bootstrap timeout at 300 s on 132. The entries cleared around 15:39 Singapore. All eight pod/container identities and source hashes remained unchanged, and two subsequent complete checks found all 115 queue gauges idle. No Store eviction occurred during this short trial and its drain; sustained cache retention is still untested here. Failed server token/cache usage stays unknown, and successful-only statistics cannot substitute for zero-error acceptance.</p>
<p>ATT33 is applied and its actual process arguments are verified: affinity remains 1,800 s and <code>--router-prefill-overload-threshold-ms</code> changes from 8000 to 0. This disables both pinned-worker and scored-cache projected-load escape; hard admission limits and external backlog/failure guards remain. ATT33 subsequently completed the full load with zero errors; its remaining TTFT queue spikes and the current priority are documented above.</p><p>'''+reportlink('20260913_073337')+''' · <a href="att32-report.md">Complete ATT32 reproduction record</a> · <a href="att32-workload-summary.json">All-admission accounting</a> · <a href="latency-att32.json">Reconstructed successful-request latency</a> · <a href="affinity-stage-cache-comparison.json">Same-workload stage and cache comparison</a>.</p>''')

section('kv-boundary','A concrete KV handoff mismatch','''<div class="callout"><strong>ATT25 reproduced the third-request failure with a byte-level difference.</strong> Two retrieval answers were correct; the third cold request reached 256 tokens without a final answer. Its regular KV hashes differ between Prefill and Decode in global layers 58–77, exactly the last Prefill pipeline stage. No performance replay followed this finding.</div>
<p>The first two requests match all 156 logical pool tensors each. The failed request matches 136 of 156: all 78 DSA key/scale tensors match, while 20 regular KV tensors differ. The final 16 token rows match even in those 20 tensors; earlier Decode bytes contain substantially more zeros. Fifteen boundary snapshots join by exact internal request and bootstrap-room identity, covering about 3.0 GB of logical KV bytes. These observations suggest an early chunk read before its GPU writes complete, but do not yet establish the precise missing range or prove the cause.</p>
<p>Source inspection found a relevant existing dependency gap: with pipeline parallelism, this deployment disables the ordinary overlap scheduler. Its non-final chunk send can precede the prior forward-completion wait; the last pipeline rank lacks the proxy-send dependency present on the other ranks. ATT26 then added a broad producer-completion wait only to Prefill. All three answers were correct and all 468 compared pool tensors matched, while Decode and frontend remained unchanged. The expected zero hidden-state layout difference persisted. This supports the missing dependency as the cause of the observed KV mismatch; three requests with synchronous fingerprint diagnostics do not establish general correctness. ATT27 replaces the broad scheduler wait with a per-segment CUDA event consumed in Mooncake’s transfer thread, after outstanding-transfer accounting and before an abort/status recheck. Thirteen CPU fixtures execute the actual send, queue and worker methods. ATT27 also returned all three correct answers with all 468 pool tensor comparisons matching. Six prior Decode metadata files were hash-verified and excluded from this new trial. All queues drained. This change is not yet a validated performance result; the isolated Prefill151/Decode192 deployment subsequently passed all 15 predeclared retrieval requests with fingerprint capture disabled. This sequential correctness result is separate from sustained-load performance.</p>
<p>All observed metadata differences concern zero-filled hidden-state buffers with different layouts: 16 float32 values on Prefill versus 6,144 bfloat16 values on Decode. This difference appears on both passing and failing requests. The six other compared fields match. Zero speculative-seed validity remains a separate question; the layout difference alone is not evidence of random transport corruption.</p>
<p>ATT24 sent no probes. Before using its diagnostic, review found that the original DSA fingerprint helper included padding and omitted valid scale bytes on partial pages. A diagnostic-only correction passed twelve CPU fixtures, including a deliberately changed final scale byte that the original helper missed. An opt-in guard limits captures to the P/D boundary, preserving the existing EAGLE configuration without per-verify dumps. These are diagnostic changes, separate from the six retained performance changes.</p>
<p><a href="kv-boundary-att25.json">Aggregate comparison and limitations</a> · <a href="diagnostic-fingerprint.patch">Diagnostic helper patch</a>. Exact source hashes, CPU fixtures, rollout manifests, all request outcomes and snapshot archives are retained under <code>/mnt/HPC/tom/pd-latency-followup-20260913/attempt25-pd-only-kv-fingerprint/</code> and <code>candidates/dsa-snapshot-layout/</code>. Hashing synchronizes CUDA and may alter a race; these request timings are not performance evidence.</p>''')
section('expanded-goal','Expanded four-node investigation','''<p>Tom added nodes 151 and 192 to 130 and 132. The goal now includes a 2P1D deployment at about 60M input / 6M uncached TPM with the same roughly 90% hit rate, ten-minute measured duration, 20-token output cap and latency/speed requirements. The target remains every Alex 20-second completion-window TTFT p50 below 4 seconds, correct outputs and zero errors, with TPOT tails investigated separately.</p>
<p>Initial checks found all four GPUs idle on each new node; all sixteen GPUs share a healthy NVLink fabric. An isolated second 1P1D deployment was installed at 12:37 Singapore for Prefill151 / Decode192, with a private 600GiB Mooncake Store and frontend port 32109. All workers became Ready and the uninstrumented correctness control passed 15/15 requests, exact cache/input coverage, and all-rank 8K graph replay. ATT28 rolled only Prefill151 to the six optimized source changes plus producer events on both send paths; Decode192, frontend and Store remained unchanged. The completed600s replay passes the strictTTFTwindow goal with the TPOT limitations above. Both owned 1P1D releases were subsequently drained, preserved and stopped. The 2P1D deployment is now installed: Prefill on 132 and 151, with one eight-GPU Decode replica spanning 130 and 192. All eight pods became Ready at 13:34:59 Singapore. The frontend registers exactly two Prefill generation instances and one Decode generation instance.</p>
<p>The fourth doubled-load selection is registered in Alex as <code>tom-capacity-v3-2p-60m-6m-10min-20260913</code>. It has 13,469 measured requests from1,254 sessions:600,193,610 input and59,992,906 modeled uncached tokens over600 seconds. Its400 distinct warmup requests add22,317,642 input tokens over120 seconds. Every one of72,325 numeric boundary probes passes the disclosed1% input/5% uncached whole-request tolerances. Sampled rolling minutes have at least335 exact16K prefix families; largest-family share is at most3.225%.</p>
<p>Alex Prepare <code>20260913_045325</code> finished at12:55:20 Singapore using16CPUworkers in112seconds, with no inference requests. All13,869 original payload frames were hash/decompression/JSON checked; all canonical bodies are distinct. Every prepared token sequence equals its verified original GLM5.3 source. Dataset ID:<code>dataset-dfa320022c5b1e8c171a2227</code>; token profile:<code>profile-0f6d63bca1c499991a2a2073</code>. The full-pack picker average51.878MTPM includes warmup; the measured schedule targets60M.</p>
<p>The first sustained-load trial exposed cache loss and queue growth; see the partial result below. Before load, all 24 fixed retrieval requests passed across all eight Decode DP ranks. Eight requests switched Prefill replicas and each reused exactly 18,048 tokens from shared storage, independently verified on all four consumer pipeline ranks. Both Prefill replicas replayed their 8K graphs, and 115 engine/frontend queue gauges were idle twice. These bounded probes establish neither general accuracy nor sustained performance. The modeled two-Prefill configuration has11.102528M local tokens each and20M shared logical L3 tokens. Ten seconds of completion delay plus five seconds of L3 publication delay passes the round-robin audit; twenty seconds of total visibility delay fails. The installed Store has two 650 GiB clients, each requesting 670 GiB RAM with a 690 GiB limit. Live metrics confirm 1,300 GiB raw capacity. Store192 initially exhausted connection retries while the master image was pulling; its one automatic restart and successful recovery are preserved. This was not an OOM or an inference failure. At the observed90%watermark and5%eviction step,2x600GiB left only19.832M logical tokens;2x650GiB leaves about21.485M before fragmentation. Exact payload cost is55,224bytes per logical token over78layers. The16M/18Mcache sensitivity fails some routing cases, so raw pool size alone is insufficient. Actual capacity, routing, pinning and L3 hit partitioning require live checks. The running Decode uses TP8/DP8/EP8 across 130/192 with 768 total max-running requests, preserving 96 per DP rank. Actual rank partitions are 0–3 and 4–7; each rank has 3,135,616 logical KV tokens. Two independent four-GPU Prefill replicas use 132/151. Operator leader/follower injection is verified against current Ready production pods without modifying them. Earlier candidates remain recorded: candidate01 fails the five-second publication sensitivity; candidates02 and03 fail seven and two sampled numeric windows respectively. Candidate04 bounds cumulative uncached-token debt across minute boundaries; it does not retime failed windows after selection.</p>
<p><a href="optimized-event.patch">Producer-event patch on top of the six optimizations</a>. The deferred path records the event before launching later independent forward work. Thirteen actual-method transport fixtures,51 ownership/lifetime checks and six producer-boundary checks passed on CPU. The event-only control and combined candidate each passed15/15uninstrumented correctness probes. The combined candidate is the new lowest-TTFT completed run, with unresolvedTPOTtails.</p>
<p><a href="two-prefill-one-decode-report.md">2P1D deployment, correctness and failure record</a>. An initial eight-token smoke ended during reasoning with no final answer; it is retained as a failed answer check. The established 256-token retrieval fixtures then passed. The supplied enable_thinking=false flag did not suppress reasoning in this runtime, so nonempty generated output at the 20-token stress cap does not imply a complete final answer.</p>
<p><a href="doubled-load-candidate-summary.json">Dataset counts, numeric audits and cache scenarios</a> · <a href="producer-fence-att26.json">ATT26 comparison</a> · <a href="producer-event-att27.json">ATT27 comparison</a> · <a href="async-kv-event.patch">ATT27 event-fence patch</a> · <a href="async-kv-event-cpu.json">Thirteen CPU fixtures</a>. Private manifests, source hashes, startup evidence and failed candidates are retained under <code>/mnt/HPC/tom/pd-latency-followup-20260913/expanded-four-node/</code> and <code>attempt27-async-kv-event/</code>.</p>''')
section('two-prefill-result','First 2P1D result: cache loss and queue growth','''<div class="callout"><strong>ATT29 is a failed partial trial.</strong> Admissions stopped after 222.899 seconds to avoid approaching Decode capacity. All 4,705 admitted requests completed; 8,764 planned requests were never admitted. No client errors, Decode rejections or new runtime restarts occurred.</div>
<p>Whole-run TTFT p50 / p99 was 10.656 / 46.960 seconds. The worst Alex 20-second TTFT p50 was 51.830 seconds during drain; 198 windows exceeded 4 seconds. Whole-run TPOT p99 was 79.386 ms, and the worst 20-second p99 was 105.482 ms. All 264 saved windows were independently reconstructed, including startup and drain.</p>
<p>The first minute matched 60M input / 6M uncached TPM and a 90% hit rate. Cache hit rate then fell to 89.26% in minute 2 and 86.87% in minute 3. Across admitted requests it was 88.194%, with 4.042M more uncached tokens than the finite plan predicted. Traffic over the admission span was approximately 60.034M input / 7.088M uncached TPM.</p>
<p>The shared Store evicted 2,137,435 physical object keys and 943.45 GB in 15 eviction passes. Some large-prefix misses occurred 10–53 seconds after their parent requests completed. The finite model's prefix-preserving eviction assumption needs validation against actual Store behavior; raw capacity alone did not ensure the modeled hit rate. Early frontend preprocessing averaged about 6 ms, while Prefill queue time grew and bootstrap / final handoff averaged about 0.64 seconds each.</p>
<p>The separate cold warmup completed 400 / 400 requests but had a TTFT p50 of 20.019 seconds. All serving queues drained, and final source, image and container checks passed after the interrupted run. The subsequent 12K chunk-only trial is recorded below; it also failed the TTFT and zero-error goals.</p><p>'''+reportlink('20260913_055201')+''' · <a href="two-prefill-partial-summary.json">Counts, latency and cache cohorts</a> · <a href="two-prefill-one-decode-report.md">Full deployment and reproduction record</a>.</p>''')

section('two-prefill-12k','12K result: Prefill overload, lower partial TPOT','''<div class="callout"><strong>ATT30 failed and was stopped early.</strong> All 3,954 admitted requests are accounted for: 3,942 succeeded and twelve received HTTP 529;  9,515 were never admitted. Every failure joins to frontend rejection of a selected Prefill worker. No Decode bootstrap failure was logged.</div>
<p>The only serving change from ATT29 was Prefill chunk/max-prefill 8,192 → 12,288 with a matching graph bucket on both replicas. Six cold/shared/cold correctness probes passed in both Prefill directions and on both physical Decode nodes; actual 12K graph replay was verified on all eight Prefill ranks. A pre-probe reset rejection caused by a readiness canary is retained separately. The following fresh warmup completed 400 / 400.</p>'''+table(['Partial measured result','ATT30'],[['Successful TTFT p50 / p99','6.458 / 23.364 s'],['Worst Alex 20s TTFT p50','22.219 s; 147 of 209 points above 4s'],['Whole / worst Alex 20s TPOT p99','19.396 / 30.110 ms'],['TPOT above 40 / above 80 ms','5 / 0 requests'],['Last admission / completion','186.547 / 209.693 s'],['Successful cache hit rate','88.9703%; 1.890M extra uncached tokens versus plan'],['Estimated offered input / known successful uncached TPM','60.038M / 6.591M; failed request cache usage unknown']])+'''<p>All 209 latency points were reconstructed, including startup and drain. These partial metrics cannot establish a full ten-minute TPOT pass. The source scheduler remained valid and had no connector queue events. All 115 serving queue gauges drained, source and container checks passed, and all collectors stopped cleanly.</p>
<p>Queue growth preceded Store eviction: the 45–60s arrival cohort already had TTFT p50 4.547 s with only 3,072 extra uncached tokens. First Store eviction occurred between 78.484 and 83.485 s. Over ATT30, counters increased by eleven eviction passes, 1,566,680 physical keys and 690.29 GB; counters from prior trials were subtracted. Early bootstrap and final-handoff means increased from about 0.5–0.7s at 8K to 0.8–1.1s at 12K. Per-stage counter means are observation-time cohorts and must not be added as an exact client TTFT decomposition.</p>
<p>Workload mix is an additional comparison limit. Candidate04 has 13,469 requests versus 11,842 for twice the best 1P1D workload: 13.739% more requests, with mean input 44,561 versus 50,710 tokens, and 1,254 versus 768 sessions. Candidate05 subsequently passed its CPU audits, was registered and tested in ATT31 with the original 8K serving configuration. It matched request rate while retaining real prompts, 60M input / 6M modeled uncached TPM, diversity and finite-cache constraints. Its measured result is below.</p>
<p>The Store audit found all eight physical objects present for 254 sampled actual pages after ATT29. This weakens widespread partial-page eviction as an explanation; transient holes remain untested. A separate prepared-token-derived key probe failed even its positive controls, so its key correspondence is unresolved and its misses cannot prove cache loss. Actual ordinary-object eviction also differs from the offline prefix-preserving model.</p><p>'''+reportlink('20260913_063354')+''' · <a href="att30-report.md">Full ATT30 reproduction record</a> · <a href="att30-partial-summary.json">Admission and cache accounting</a> · <a href="latency-att30.json">Raw-derived latency summary</a> · <a href="two-prefill-stage-comparison.json">Stage comparison</a> · <a href="workload-mix-comparison.json">Workload comparison</a>.</p>''')

section('two-prefill-matched-rate','Matched request rate: more host and shared-cache work','''<div class="callout"><strong>ATT31 failed sustained TTFT and cache goals.</strong> The backlog guard stopped admissions after 149.955 seconds. All 2,968 admitted requests succeeded; 8,874 planned requests were never admitted. No frontend overload or bootstrap failure was observed.</div>
<p>Candidate05 uses 11,842 measured requests, exactly twice ATT28, with a mean input of 50,695 tokens versus 50,710. All 12,242 warmup/measured token sequences match the prepared real source, and every payload frame was verified. However, the candidate retains 1,324 measured sessions versus 768 for twice ATT28; request-rate matching does not match the cache working set. Serving values exactly match ATT29: two 8K Prefills and one eight-GPU Decode.</p>'''+table(['Partial measured result','ATT31'],[['Whole TTFT p50 / p99','5.294 / 18.525 s'],['Worst Alex 20s TTFT p50','16.477 s; 120 of 170 points above 4s'],['Whole / worst Alex 20s TPOT p99','20.287 / 22.711 ms'],['Individual TPOT above 40 / 80 ms','4 / 1 requests'],['Actual cache hit / net deficit','89.1981% / 1.215M tokens'],['Approximate offered input / actual uncached TPM','60.069M / 6.489M'],['Successful / failed / unadmitted','2,968 / 0 / 8,874']])+'''<p>Every saved Alex window was independently reconstructed, including startup and drain. The first arrival-minute TTFT p50 was 2.996s at 90.0028% cache reuse; the next minute reached 6.884s at 89.0257%. All 115 queue gauges drained, eight pod/container identities and source hashes remained unchanged, and collectors closed cleanly. The partial TPOT figures do not establish a ten-minute pass.</p>
<p><strong>Equal uncached TPM did not mean equal cache-transfer work.</strong> In roughly the first minute, ATT28 processed 2.821M new tokens with 25.400M GPU-cache hits and no host/shared-storage hits. ATT31's two Prefills processed 2.753M and 2.811M new tokens, but fetched a combined 8.285M cached tokens from host memory or shared storage. Mean Prefill queue time in the 30–60s scrape interval was 1.560 / 1.813s versus 0.141s in ATT28. These are observation-time counter cohorts, not an additive TTFT decomposition.</p>
<p>Queue growth again preceded shared-Store eviction: the 30–45s arrival cohort already had p50 4.064s with only 704 extra uncached tokens. First eviction occurred between 78.829 and 83.837s. Eight eviction passes removed 1,139,816 physical keys and 503.38GB during this trial. Synthetic-fixture key correspondence now passes for all eight objects on all 282 complete pages in each of two fixtures; the old real-request key lookup remains unresolved.</p>
<p>ATT32 subsequently tested the installed frontend's 1,800-second session-affinity option with candidate05 and all worker/cache settings fixed. Only the frontend restarted. The completed negative result and its routing conflict are documented next.</p><p>'''+reportlink('20260913_070704')+''' · <a href="att31-report.md">Full ATT31 reproduction record</a> · <a href="att31-workload-summary.json">Workload accounting</a> · <a href="latency-att31.json">Reconstructed latency</a> · <a href="request-rate-control-stages.json">Stage comparison</a> · <a href="request-rate-control-cache-tiers.json">Cache tiers</a>.</p>''')

contract=json.loads((ROOT/'evidence/contract-percentiles.json').read_text())
contract_table=table(['Run','P50','P75','P90','P99','Mean'],[[reportlink(r['run_id'])]+[f"{r['ttft_seconds'][str(p)]:.3f} s" for p in [50,75,90,99]]+[f"{r['ttft_mean']:.3f} s"] for r in contract])
section('contract','Contract figures and current compliance limits','''<p>Tom clarified the column order as Metric, P50, P75, P90, P99, Average. The supplied TTFT targets map to 4 / 8 / 12 / 30 seconds; no average value was supplied. The stated contract tolerance is less than 1.2 times those targets. We retain the stricter research objective of short-window p50 below 4 seconds.</p>
<p>The two earlier 1P1D runs in this table meet all four supplied whole-run TTFT targets even before the 1.2 multiplier. This does not replace the stricter short-window research goal.</p>'''+contract_table+'''<p>The supplied speed/latency pairs are 55 tokens/s ↔ 18 ms, 30 ↔ 33 ms, and 25 ↔ 40 ms, with a speed-retention requirement above 90%. Three pairs do not fully populate the five columns. Direct OTPS percentile order reverses when converted to TPOT, and rounded reciprocals should not be treated as exact same-percentile identities. No complete contract certification is claimed yet.</p>'''+table(['ATT20 raw request metric','Observed'],[['TTFT ≤ 4 s','96.10% of successful requests'],['TPOT ≤ 18 ms','5,880 / 5,921 = 99.31%'],['TPOT ≤ 33 ms','5,911 / 5,921 = 99.83%'],['TPOT ≤ 40 ms','5,911 / 5,921 = 99.83%']])+'''<p>These are descriptive fractions using the client metric, not a reinterpretation of the contract. A request-fraction criterion and a requirement on every short-window p99 are different requirements.</p>''')
rows=[]
for r in data['runs']:
 rows.append([esc(r['arm'].replace('_',' ')),reportlink(r['run_id']),str(r['successes'])+' / '+str(r['failures']),f"{r['ttft_global_ms']['p50']/1000:.3f}",f"{r['worst_portal_ttft']['ttft']['p50']/1000:.3f}",f"{r['tpot_global_ms']['p99']:.2f}",f"{r['worst_portal_tpot']['tpot']['p99']:.2f}",str(r['tpot_requests_above40'])])
section('results','All uninstrumented completed comparisons',table(['Arm','Alex report','Success / fail','TTFT p50 s','Max 20s p50 s','TPOT p99 ms','Max 20s p99 ms','TPOT >40 ms requests'],rows)+'''<p><a href="latency-comparison.json">Download the aggregate evidence</a> · <a href="analyze_latency.py">Independent reconstruction script</a>. Script input timing exports remain in the private research directory; they contain request identifiers and are intentionally not embedded here.</p>''')
section('attempts','Diagnostics, failed approaches and retained history','''<p>The original phase covered 21 attempt directories and 18 completed ten-minute trials: 14 uninstrumented trials, four diagnostics, one interrupted diagnostic, one startup failure and one warmup-only anomaly. The preceding baseline is separate.</p>'''+table(['Attempt','Purpose / result'],[
['01','Bounded GPU diagnostic interrupted after profiler export disruption and a native-hash thread fault. Not an acceptance run; scoped Prefill recovery retained.'],
['02 / 03','Depth 1, then breakable CUDA graphs. Still accumulated backlog and rejected requests.'],
['04','CPU diagnostic: low OS runqueue wait weakened CPU scheduling starvation as the main explanation.'],
['05 / 06','Earlier control bundle, then depth 0. Depth 0 worsened sustained throughput.'],
['07 / 08','Launch before old-output handling, then enable breakable graphs on that source. Improvement, but still failures.'],
['09 / 10','Trace verbosity and 27-phase CPU timing diagnostics. Timing measures include synchronization waits.'],
['11','Earlier last-rank output: first full zero-failure run, but sustained TTFT still high.'],
['12','Earlier current-proxy publication failed startup through a lazy NCCL CPU-metadata wait cycle; rolled back.'],
['13','Control-safe proxy variant completed but regressed latency; excluded from best lineage.'],
['14 / 15','Early cached prefix and all-rank output relay tested separately. Prefix improved latency; all-rank relay alone did not.'],
['16 / 16b','Combined changes. First warmup had one missing-TTFT/empty-visible-output event; one predeclared fresh-reset retry completed. Original anomaly remains unresolved.'],
['17 / 18','Final-map reuse, then 30-phase diagnostic; page-map dependency wait motivated overlap work.'],
['19 / 20','Same-iteration map-copy overlap; unchanged fresh-cache repeat. Both pass the original 60s criterion, both retain shorter-window spikes.'],
])+'''<p>Historical counters recorded no quota throttling in the experiment containers or immediate pod parents. Sampled scheduler-main-thread runqueue wait was very small; this does not exclude locks, the GIL, synchronization or serial work. Initial queue growth was visible in Prefill before Decode saturation. Late Decode-forward means stayed near 0.2 seconds, while Prefill waiting grew markedly in early unsuccessful arms.</p>
<p>Observed bootstrap/final-transfer means in the final runs remain about 0.58 / 0.60 seconds. The original roughly 1.2-second handoff delays were reduced, not eliminated. The separate Decode-rejection cleanup issue was filed and deferred; successful runs do not prove it fixed.</p>''')
section('validation','Correctness checks and evidence limits','''<ul><li>51 CPU lifetime, payload and cursor checks; four deliberately unsafe variants rejected.</li><li>30 actual-loop ordering cases and two complete source/AST restoration checks.</li><li>Native CUDA copy semantics and graph/map-path activation on all four Prefill ranks.</li><li>Three long-context retrieval probes: two cold and one shared-prefix case. Final answers, payload hashes and input/cache counts matched. Reasoning text and output lengths varied; bitwise or token-level equivalence was not established.</li><li>Each final run: zero failures, no empty successful outputs, DONE observed, all TTFT values present, valid generator, 22 observed rejection/error counter series without increments, 56 queue/running gauges idle twice, three bound containers Ready with zero restarts.</li></ul>
<p>Correctness retrieval probes used up to 256 output tokens; the canonical performance workload remained capped at 20. Histories retain the failed short-budget probe and warmup anomaly. Missing counters remain unobserved, not zero. Trace requery recovered three later-visible spans; both query sets were saved. Startup evidence after log rotation was inherited only for the unchanged container, while current identities and source/spec hashes were rechecked.</p>''')
section('reproduce','Reproduction and rollback record','''<p><strong>Current milestone and code records:</strong> <a href="milestones.md">Milestone ledger</a> · <a href="code-change-ledger.md">Code/configuration ledger</a> · <a href="att33-snapshot-verification.json">ATT33 archive verification</a> · <a href="att34-snapshot-verification.json">ATT34 archive verification</a>. ATT34 preserves 156 files, all hashes verified, with archive SHA256 <code>83b5739883d058e1acd57e854bb4e9464358fcc2571c1ecabf27ed1f180466de</code>. The private ATT33 archive contains 149 recipe, code and evidence files; every archived entry was verified against its SHA256 manifest. Archive SHA256: <code>9ffd2b4940ea79a0b3fa1215cb67b68e4e301a7998a667ea91f5350282d046be</code>. Current rollout state is separate from closed milestone snapshots. <a href="complete-against-frozen.patch">Combined retained-code patch against frozen SGLang</a> · <a href="complete-patch-verification.json">Exact reconstruction verification</a>.</p><p>Use the following private paths on Tom’s shared workspace as artifact locators. They are not browser links. The original archive is the complete record; this public page contains the report, reviewed patch and selected non-secret validation artifacts.</p>'''+table(['Artifact','Private locator'],[
['Complete investigation',code(OLD)],['Follow-up',code(ROOT)],['Frozen SGLang base',code('/mnt/HPC/tom/experiments/glm53-optim-exp-1p1d/sources/sglang-6d08e28b0c0691899973e3f11bf01fdbdf192a63')],
['Six-optimization candidate',code(str(candidate))],['ATT28 best candidate',code(str(ROOT/'candidates/optimized-async-kv-event'))],['ATT28 exact recipe',code(str(ROOT/'attempt28-lane-b-optimized-event/preparation'))],['2P1D exact recipe and source overlays',code(str(ROOT/'expanded-four-node/two-prefill-one-decode/preparation'))],['Best exact Helm recipe',code('attempt19-same-iteration-map-copy/rollout/PREPARED.json')],['Best chart and ordered values',code('attempt19-same-iteration-map-copy/chart/')+'; '+code('rollout/before-values.json')+' then '+code('rollout/trial-values.json')],
['Expected deployment',code('attempt19-same-iteration-map-copy/rollout/after-render.yaml')],['Run and validation records',code('attempt19-same-iteration-map-copy/REPORT.md')+' / '+code('attempt20-map-copy-repeat/REPORT.md')],
['Every attempt','Original root: '+code('EXPERIMENT-INDEX.md')+', '+code('DECISION-LEDGER.md')+', '+code('BEST-RUN-SETTINGS.md')],
['Raw portal events',code('/var/lib/replay/results/<run-id>/details/raw_events.jsonl')+' in the Alex pod'],
['New timing exports',code(str(ROOT/'evidence/<run-id>/timing-events.jsonl'))],
['Historical CPU audit',code('/mnt/HPC/tom/ttft-bootstrap-handoff-20260911.yhMGqD/saved-evidence/historical-cpu-arithmetic/REPORT.md')],
['Complete archive',code('settings-retention-20260913-061635.tar.gz')+' under the original root'],
['Archive SHA-256',code('5d59acb2fbabd8dd4552202f68331eb17c26c91ad9bf2929459259cd672091f3')],
])+'''<p>The final archive verified 2,113 checksummed files across 21 attempt directories; the preserved chart and ordered values reproduced the recorded render byte-for-byte. Its dependencies include model data, images, credentials and pre-existing overlays; the archive is not a standalone runnable container.</p>
<ol><li>Check current cluster, namespace, Helm owner, node placement, bound pod/container identities, source hashes and idle queues. The owned release is <code>maas-dev-tom/glm53-optim-exp-1p1d</code>.</li><li>Verify the archive and frozen sources. Apply the cumulative patch only against its recorded base; the saved temporary-directory apply check reconstructed both candidate files exactly.</li><li>Render the owned chart with the recorded values in order. Inspect the complete diff and retain the current rollback recipe before applying a scoped change. Historical commands carry old identities and must not be replayed blindly.</li><li>Verify Ready containers, exact source/image hashes, all-rank graph activation, fixed cache capacity and retrieval correctness. Retain the other runtime overlays.</li><li>Clear only the owned caches, run the canonical 100-request warmup and require all TTFTs, then run the full 5,921-request replay through Linux headless CDP 19341. The maintained helper is <code>/mnt/HPC/tom/.local/share/alex-headless/cdp.mjs</code>.</li><li>Collect raw timing events, live metrics, generator diagnostics, trace joins and exact clocks. Audit both 20s completion and 60s arrival windows, whole-run percentiles, TPOT tails and failures.</li><li>Drain queues, close owned collectors and preserve the outcome even on regression. Use the recorded prior chart/values for rollback after fresh ownership checks.</li></ol>
<p>Reproduction script: <code>python3 worker/analyze_latency.py</code> from this follow-up record. It reconstructs all saved chart TTFT p50 and TPOT p99 points and verifies them against the exported portal timeseries, rather than assuming the labels describe the same population.</p>''')
section('provenance','Image, source and publication provenance',table(['Component','Immutable identity'],[
['SGLang frozen commit',code('6d08e28b0c0691899973e3f11bf01fdbdf192a63')],
['Final PP scheduler SHA-256',code('b3b95b176a6185a34b75664cda8aecc921989b9e50fa5efea268d3e207c07d41')],
['Six-optimization Prefill SHA-256',code('eb8ccfa08e3e5373d47123ed5fb74d4a19b84b00c9ab1025b9875033dc2bc372')],
['ATT28 / 2P1D Prefill SHA-256',code('03a7e10add300de5bb51cefe767e49dd84187b375c998c7a16341230ea603ac3')],
['Producer-event transport SHA-256',code('f34c28b27d812835d7b36d8074c12853aeb169a7c3261046c773262d304581ff')],
['Cumulative patch SHA-256',code('d004b159163dedaee15ddb3a0ecf91cea1e171fab9b0e77b156a0989cbb3a531')],
['Worker image digest',code('sha256:21bee33e6e20c10481d84d660e03b4675d5ff817ce2cd0a4cc859eb9e1ae62e0')],
['Frontend image digest',code('sha256:8ab5025a0233062fa6224b345e2ac22a65e823d40f4dcd6242128afc491440b5')],
['Preserved generator commit',code('a50880df29554b03a2cf6d455abf9dfb4576ad27')],
['Deployed benchmark source SHA-256',code('2f5767eb8e54779ab171ef3e2bb27f4464e29d1f9c5acd4c94a9d8b2afce2af2')],
['Authoring source',code(str(Path(__file__).resolve()))],
])+'''<p>The shared generator checkout has a legacy remote and an unrelated local modification; it was not pulled or mutated for this comparison. Its benchmark source matched the deployed file byte-for-byte. The first timing export connection interrupted during ATT20; the partial file was retained and ATT20 was re-exported completely. All 15 final timing exports contain exactly 5,921 records.</p>''')
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f7fa;color:#1b2939;font:16px/1.65 system-ui,sans-serif}header{background:#142a40;color:white;padding:28px 40px}header a{color:#c5e3f8}header h1{font-size:32px;margin:8px 0}header p{max-width:1000px;color:#c7d5e5;margin:5px 0}.layout{display:grid;grid-template-columns:225px minmax(0,1120px);gap:32px;max-width:1435px;margin:28px auto;padding:0 22px}aside{position:sticky;top:20px;align-self:start;border-left:3px solid #cbd7e3;padding:12px 15px;background:#edf2f6}aside a{display:block;font-size:13px;padding:5px 0;text-decoration:none;color:#425a70}article{min-width:0}section{background:white;padding:25px 30px;margin-bottom:22px;border:1px solid #dce4eb;border-radius:9px;scroll-margin-top:18px}h2{font-size:25px;margin:0 0 15px}h3{font-size:17px;margin:0 0 8px}p{margin:12px 0}a{color:#11698b}code{font:12px/1.6 ui-monospace,monospace;background:#eff3f6;padding:2px 4px;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;vertical-align:top;padding:10px 12px;border-bottom:1px solid #dfe6ed}th{background:#eef3f7;color:#365064}tbody tr:nth-child(even){background:#fafbfc}.table-scroll{overflow-x:auto}.callout{padding:16px 20px;border-left:4px solid #bf6c27;background:#fff6e9}.equation{display:flex;flex-wrap:wrap;gap:14px;align-items:center;padding:17px;background:#eef4f8;border-radius:6px}.unit{color:#587186;font-size:13px}select{max-width:100%;padding:8px;border:1px solid #b7c9d8;border-radius:5px;font:14px system-ui}.chart-card{padding:18px;border:1px solid #dfe6ed;margin-top:16px;border-radius:6px}svg{display:block;width:100%;height:auto}footer{color:#607387;margin:20px 0}li{margin:7px 0}'''
js='''const DATA=JSON.parse(document.getElementById('chart-data').textContent),sel=document.getElementById('run-select');function draw(){const p=DATA[sel.value].points;for(const [id,col,scale,threshold,unit,color] of [['ttft-chart',1,1000,4,'s','#166b8e'],['tpot-chart',2,1,40,'ms','#9b4c2d']]){const svg=document.getElementById(id),max=Math.max(threshold*1.3,...p.filter(x=>x[col]!=null).map(x=>x[col]/scale))*1.08,end=Math.max(...p.map(x=>x[0])),X=t=>50+825*t/end,Y=v=>215-190*v/max;let s='';for(let i=0;i<=4;i++){const v=max*i/4;s+=`<line x1="50" x2="875" y1="${Y(v)}" y2="${Y(v)}" stroke="#e1e8ee"/><text x="43" y="${Y(v)+4}" text-anchor="end" font-size="11" fill="#556b7d">${v.toFixed(1)}</text>`}for(let t=0;t<=end;t+=120)s+=`<text x="${X(t)}" y="239" text-anchor="middle" font-size="11" fill="#556b7d">${t}s</text>`;s+=`<line x1="50" x2="875" y1="${Y(threshold)}" y2="${Y(threshold)}" stroke="#b54032" stroke-dasharray="5 4"/><text x="870" y="${Y(threshold)-5}" text-anchor="end" font-size="11" fill="#b54032">${threshold} ${unit}</text>`;s+=`<polyline fill="none" stroke="${color}" stroke-width="2" points="${p.filter(x=>x[col]!=null).map(x=>X(x[0])+','+Y(x[col]/scale)).join(' ')}"/>`;svg.innerHTML=s;svg.onmousemove=e=>{const rect=svg.getBoundingClientRect(),t=((e.clientX-rect.left)/rect.width*900-50)/825*end,q=p.reduce((a,b)=>Math.abs(b[0]-t)<Math.abs(a[0]-t)?b:a);document.getElementById('point-readout').textContent=`${sel.value} · elapsed ${q[0]} s · TTFT p50 ${q[1]==null?'N/A':(q[1]/1000).toFixed(3)+' s'} · TPOT p99 ${q[2]==null?'N/A':q[2].toFixed(2)+' ms'}`}}}sel.onchange=draw;draw();'''
nav=''.join('<a href="#'+id+'">'+esc(title)+'</a>' for id,title,_ in sections)
body=''.join('<section id="'+id+'"><h2>'+esc(title)+'</h2>'+content+'</section>' for id,title,content in sections)
now=datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).strftime('%Y-%m-%d %H:%M Singapore')
page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Reproducible GLM-5.3 GB300 TTFT and TPOT optimization investigation, all trial outcomes, source patch and corrected short-window acceptance."><title>GLM-5.3 GB300: TTFT and TPOT investigation</title><style>'+css+'</style></head><body><header><a href="../">MaaS Docs</a><h1>GLM-5.3 GB300: TTFT and TPOT investigation</h1><p>30M/3M baseline · 60M/6M two-Prefill investigation · code, evidence and reproduction</p><p>Updated '+now+' · research active · all times Singapore unless explicitly UTC</p></header><div class="layout"><aside aria-label="Contents">'+nav+'</aside><article>'+body+'<footer>Generated from preserved experiment artifacts. Open issues and negative results remain part of the record.</footer></article></div><script type="application/json" id="chart-data">'+json.dumps(chart_data).replace('</','<\\/')+'</script><script>'+js+'</script></body></html>'
(OUT/'index.html').write_text(page)
print(json.dumps({'output':str(OUT),'sections':len(sections),'bytes':len(page.encode()),'public_url':'https://tomyoung903.github.io/maas_docs/'+OUT.name+'/'}))
