"""Build a portable public investigation record from explicit, non-secret evidence."""
from pathlib import Path
import datetime
import hashlib
import html
import json
import re
import shutil

ROOT=Path(__file__).resolve().parents[1]
OLD=Path('/mnt/HPC/tom/pd-queue-overnight-20260912.twotxxas')
OUT=Path('/home/tom/maas_docs/docs/glm53-gb300-ttft-tpot-optimization')
OUT.mkdir(parents=True,exist_ok=True)
esc=html.escape
data=json.loads((ROOT/'evidence/latency-comparison.json').read_text())
published={**data,'runs':[{k:v for k,v in r.items() if k!='worst_requests'} for r in data['runs']]}
(OUT/'latency-comparison.json').write_text(json.dumps(published,indent=2)+'\n')
candidate=OLD/'candidates/same-iteration-map-copy'
for name in ['cumulative-against-frozen.patch','cumulative-patch-check.json','lifetime-results.json','negative-controls.json','ordering-results.json','source-scope-results.json']:
    shutil.copyfile(candidate/name,OUT/name)
shutil.copyfile(ROOT/'worker/analyze_latency.py',OUT/'analyze_latency.py')
shutil.copyfile(ROOT/'worker/decompose_spike_traces.py',OUT/'decompose_spike_traces.py')
shutil.copyfile(ROOT/'worker/analyze_output_profiles.py',OUT/'analyze_output_profiles.py')
trace_data=json.loads((ROOT/'evidence/spike-traces/decomposition.json').read_text())
(OUT/'trace-cohort-summary.json').write_text(json.dumps(trace_data['summary'],indent=2)+'\n')
for rid,suffix,name in [('20260913_023856','','diagnostic-att21.json'),('20260913_030350','-partial','negative-att22.json')]:
    follow=json.loads((ROOT/'evidence'/('latency-comparison-'+rid+suffix+'.json')).read_text())
    follow['runs']=[{k:v for k,v in row.items() if k!='worst_requests'} for row in follow['runs']]
    (OUT/name).write_text(json.dumps(follow,indent=2)+'\n')
shutil.copyfile(ROOT/'attempt22-prefill6k/rollout/trial-values.json',OUT/'prefill6k-values.json')
shutil.copyfile(ROOT/'attempt25-pd-only-kv-fingerprint/evidence/FINDINGS.json',OUT/'kv-boundary-att25.json')
shutil.copyfile(ROOT/'candidates/dsa-snapshot-layout/diagnostic-layout.patch',OUT/'diagnostic-fingerprint.patch')
shutil.copyfile(ROOT/'attempt26-nonfinal-forward-fence/evidence/FINDINGS.json',OUT/'producer-fence-att26.json')
shutil.copyfile(ROOT/'attempt27-async-kv-event/evidence/FINDINGS.json',OUT/'producer-event-att27.json')
shutil.copyfile(ROOT/'candidates/pp-async-kv-event/async-kv-event.patch',OUT/'async-kv-event.patch')
shutil.copyfile(ROOT/'candidates/pp-async-kv-event/CPU-RESULT.json',OUT/'async-kv-event-cpu.json')
shutil.copyfile(ROOT/'expanded-four-node/dataset/SUMMARY.json',OUT/'doubled-load-candidate-summary.json')
shutil.copyfile(ROOT/'candidates/optimized-async-kv-event/event-on-six-patches.patch',OUT/'optimized-event.patch')
shutil.copyfile(OLD/'evidence/map-copy-replication.json',OUT/'replication.json')
shutil.copyfile(Path(__file__),OUT/'build_report.py')
sha={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in OUT.iterdir() if p.is_file() and p.name not in ['index.html','SHA256SUMS']}
(OUT/'SHA256SUMS').write_text(''.join(f'{v}  {k}\n' for k,v in sorted(sha.items())))
sections=[]
def section(id,title,body):sections.append((id,title,body))
def table(headers,rows):
    return '<div class="table-scroll"><table><thead><tr>'+''.join('<th>'+esc(str(h))+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def code(x):return '<code>'+esc(str(x))+'</code>'
def reportlink(rid):return '<a href="http://43.156.43.133:31019/replay/runs/'+rid+'/report?view=overview&amp;columns=overview">'+rid+'</a>'
section('status','Current result and open work','''<div class="callout"><strong>Research reopened on 13 September 2026.</strong> The two final ten-minute trials passed every checked 60-second arrival window, but they did not keep every Alex chart point below 4 seconds. Alex uses a different population: trailing 20-second completion windows. The stricter short-window objective remains open.</div>
<p>The best overall client TTFT run is ATT19; ATT20 repeats the same code and settings after a fresh scoped cache reset. Both achieved 5,921 successes, zero failures and complete TTFT observations. Neither is a proof for unlimited duration or other workloads.</p>'''+table(['Run','Global TTFT p50 / p99','Worst 60s arrival p50','Worst Alex 20s p50','Worst Alex 20s TPOT p99'],[
[reportlink('20260912_214223'),'2.499 / 4.698 s','3.767 s','4.412 s','82.41 ms'],
[reportlink('20260912_220009'),'2.604 / 4.504 s','3.540 s','4.238 s','83.39 ms']])+'''<p>A new recovery retrieval anomaly is being investigated before further performance tuning. The remaining priorities are attribution of the TPOT stalls, reduction of TTFT spikes, and preservation of every attempted configuration. No follow-up serving change is represented as validated on this page.</p>''')
section('workload','Fixed workload and serving configuration',table(['Item','Recorded setting'],[
['Nodes / allocation','Prefill 132: four GB300 GPUs; Decode 130: four GB300 GPUs'],
['Model','zai-org/glm-5.3; NVFP4 weights; FP8 e4m3 KV'],
['Prefill','PP4 / TP1 / DP1; async depth 1; maximum running 80'],
['Prefill scheduling','8,192-token chunks and max-prefill; breakable CUDA graphs at 512, 1024, 2048, 4096, 8192'],
['Prefill memory','Memory fraction 0.85; 64-token pages; observed GPU KV capacity 9,252,096 tokens per rank'],
['Decode','TP4 / DP4 / PP1; maximum running 384; memory fraction 0.9'],
['Decode speculation','Pre-existing EAGLE; 3 steps; top-k 1; 4 draft tokens; speculative attention mode decode. Prefill has no speculative-algorithm flag.'],
['HiCache / transport','Ratio 1.5; direct; '+code('page_first_direct')+'; '+code('write_through')+'; private Mooncake'],
['Dataset',code('tom-capacity-aware-v2-30m-3m-10min-20260911')],
['Dataset / token profile IDs',code('dataset-22913a80631e1384c956d887')+' / '+code('profile-bed998021231ed619ee5ec5c')],
['Measured replay','600 seconds; 5,921 requests; maximum concurrency 1024; replay speed 1; output cap 20; timeout 120 seconds'],
['Warmup','Separate 100-request / 120-second warmup, maximum concurrency 128, after scoped cache reset'],
['Identity semantics','Session header enabled; unique prefix disabled; cache probe disabled; original source prompts retained'],
['Measured tokens','300,255,283 input; 270,284,992 cached; 29,970,291 uncached in each final run'],
['Offered / useful input','30.0255283M input TPM and 2.9970291M useful uncached TPM over the admission interval; full completion-span uncached TPM 2.9865M / 2.9874M'],
])+'''<p>The 20-token output cap predates this optimization investigation. Short output and stream coalescing limit extrapolation of these TPOT results to long generations. The input requests replay recorded history; generated outputs do not become later request inputs.</p>''')
section('changes','Six retained code changes',table(['Change','Mechanism','Observed evidence'],[
['Earlier control publication','Publish the entire ordered request/bootstrap/release bundle before chunk maintenance.','Removes dependency-independent publication delay; not a standalone solution.'],
['Forward before old-output processing','Launch the next explicit independent Prefill input before processing prior outputs; guard mixed/dependent modes.','Depth 1 is retained while launch order changes; depth 0 alone regressed.'],
['Earlier prior-output publication','Publish ready prior outputs before current activation receive. Initially last rank, later extended across ranks.','Largest observed step: global p50 10.553 → 4.405 s. All-rank extension alone did not show a gain.'],
['Earlier cached-prefix KV send','Transfer already resident prefix KV before waiting for suffix activations.','Observed global p50 4.405 → 3.153 s. Existing cursor and fallback path retained.'],
['Final page-map reuse','Reuse an already gathered final DSA page-map suffix instead of copying it twice.','No demonstrated standalone latency improvement.'],
['Same-iteration non-final map overlap','Enqueue an owned page-index gather and pinned CPU copy, prepare/launch independent work, then join and publish before cleanup.','ATT19 was the first 60-second-window pass; same-code ATT20 replicated it.'],
])+'''<p>Counted by final behavior, there are six optimizations across <code>scheduler_pp_mixin.py</code> and <code>prefill.py</code>. The cumulative diff has 351 insertions and 74 deletions; line counts include guards and moved/indented code. Development preserved 12 source variants: ten performance candidates and two timing-instrumentation variants. This is not a count of commits or experiments.</p>
<p>The small page map identifies where KV pages live; this optimization does not copy the bulk KV cache into host memory. It preserves the page-map copy dependency and owns scratch/pinned buffers until completion, validates request/sender/row generation and cursors, and flushes or cancels before result handling, release, or a subsequent loop iteration. Alternate allocators, transports and unsupported modes retain the original path. Subsequent ATT25–27 work identified a separate bulk-KV producer dependency gap; the old page-map wait alone does not fence those bytes. ATT28 combines both producer-event paths with these six optimizations.</p>
<p><a href="cumulative-against-frozen.patch">Download the complete optimization patch</a> · <a href="cumulative-patch-check.json">Exact reconstruction check</a> · <a href="SHA256SUMS">Artifact checksums</a>. The main SGLang branch was not modified or merged; tests used Helm-owned source overlays. Other pre-existing runtime overlays remain required dependencies.</p>''')
section('measurement','Definitions and corrected acceptance scope','''<p><strong>Primary user latency:</strong> raw client TTFT runs from completed request-body upload to first meaningful generation event. Upload, connection setup, usage-only messages and DONE are excluded. Frontend and SGLang timers start and stop at different boundaries; coarse Grafana histogram percentiles must not be substituted for raw client percentiles.</p>
<p><strong>Alex chart:</strong> trailing 20-second windows, grouped by protocol completion time, evaluated every second; sparse windows with fewer than three samples are null. Percentiles use linear interpolation. The follow-up independently rebuilt every saved chart point for all 15 uninstrumented runs, including the preceding baseline.</p>
<p><strong>Earlier acceptance:</strong> 60-second windows grouped by request arrival, with latency followed to completion. ATT19 and ATT20 each passed 21,240 checked boundaries. This remains a valid narrow result, but does not imply the shorter chart windows pass.</p>
<div class="equation"><span>TPOT</span><span>=</span><span>1,000 × (last generation time − first generation time) / (output tokens − 1)</span><span class="unit">ms/token</span></div>
<p>The TPOT distribution is across successful requests with more than one output token. It is not the distribution of every individual inter-token gap. Multiple tokens can share one observed stream-event timestamp. About 46% of requests in these short-output trials have zero observed first-to-last span; that is coalescing at the client boundary, not infinite physical decode speed.</p>
<p>Cross-run changes below are observational, not randomized or counterbalanced causal estimates. Baseline failures also change the successful-request population. The latest successful runs match all 5,921 request identities and input/cache counts.</p>''')
chart_data={r['run_id']:{'label':r['arm'],'points':[[p['t'],p['ttft']['p50'],p['tpot']['p99']] for p in json.loads((ROOT/'evidence'/r['run_id']/'timeseries.json').read_text())['distribution_sliding']['points']]} for r in data['runs']}
for rid,label in [('20260913_023856','ATT21 CPU diagnostic'),('20260913_030350','ATT22 6K: interrupted negative trial; 3289 admitted')]:
    chart_data[rid]={'label':label,'points':[[p['t'],p['ttft']['p50'],p['tpot']['p99']] for p in json.loads((ROOT/'evidence'/rid/'timeseries.json').read_text())['distribution_sliding']['points']]}
section('curves','Inspect the short-window spikes','''<p>Select a run to inspect the same saved 20-second completion windows used by Alex. Hover over a plot for the nearest sample. These figures preserve the spikes.</p><label>Run <select id="run-select">'''+''.join('<option value="'+rid+'"'+(' selected' if rid=='20260912_220009' else '')+'>'+esc(rid+' · '+r['label'].replace('_',' '))+'</option>' for rid,r in chart_data.items())+'''</select></label><div class="chart-card"><h3>TTFT p50 · seconds</h3><svg id="ttft-chart" viewBox="0 0 900 250" role="img" aria-label="TTFT p50 over elapsed seconds"></svg></div><div class="chart-card"><h3>TPOT p99 · milliseconds</h3><svg id="tpot-chart" viewBox="0 0 900 250" role="img" aria-label="TPOT p99 over elapsed seconds"></svg></div><p id="point-readout" aria-live="polite">Elapsed seconds from first measured request-body send.</p>''')
section('tpot','TPOT stall evidence and regression question','''<p>The repeat has ten requests above 40 ms TPOT and four above 80 ms. Its whole-run p99 is 17.236 ms, but the worst 20-second p99 is 83.391 ms. A small cluster of stalled streams can therefore dominate a short-window p99 without changing the whole-run p99 much.</p>
<p>At approximately 350.937–352.463 elapsed seconds, four active streams share a 1.526-second gap in all observed token receipts. Sixteen new requests are dispatched during that gap. This argues against a complete freeze of the load-generator event loop. The exact trace joins below further localize the delay.</p>
<p><strong>The stall pattern existed before the retained source patches:</strong> the depth-2 baseline already had three individual TPOT values above 80 ms; the depth-1 configuration-only trial had a 90.31 ms short-window p99. This disproves that the final map-copy patch first introduced the phenomenon. It does not establish that the patches have zero effect on its frequency or clustering.</p>
<p>Whole-run TPOT p99 improved from 21.39 ms in the original depth-2 baseline to 17.34 / 17.24 ms in the final runs. Exact joins recovered 37 traces / 1,998 spans. The ten TPOT-tail requests have Decode-forward durations of 0.189–0.334 seconds. Every enclosing Decode request ends 1.022–1.460 seconds after its Decode Scheduler span ends, measured within the same SGLang service. This avoids relying on client/server clock alignment for that gap. The evidence localizes much of the stall after Decode scheduling, in output handling/delivery; it does not yet identify the blocking function.</p>
<p>The TTFT-hot cohort instead has mean Prefill waiting of 2.091 seconds, versus 0.098 seconds in a nearby control cohort. At the worst TTFT chart point, TPOT p99 is only 16.56 ms. At the worst TPOT point, TTFT p50 is 2.995 seconds. The two spike mechanisms should be investigated separately. Both final runs have identical 20-second arrival-window uncached-load ranges of approximately 2.794–3.172M TPM, which weakens a large offered-load burst as the explanation.</p>
<p><a href="trace-cohort-summary.json">Trace cohort summary</a> · <a href="decompose_spike_traces.py">Reproduction script</a>. Exact request/span identifiers remain in the private trace evidence directory. Python garbage collection remains one candidate mechanism, not an established cause.</p>''')
section('followup','Follow-up diagnostic and next controlled trial','''<p>ATT21, '''+reportlink('20260913_023856')+''', completed after an unchanged-runtime 100-request warmup. All 5,921 requests succeeded with complete TTFT, output and DONE; identities and input/cache counts matched ATT20. The generator was valid, all 22 observed error/rejection series had zero increments, 56 queue gauges were idle twice, and all three original containers remained Ready with zero restarts. Its collectors are closed.</p>'''+table(['ATT21 diagnostic metric','Result'],[['Global TTFT p50 / p99','2.533 / 4.554 seconds'],['Worst 20s completion TTFT p50','4.299 seconds at 444s; 163 requests; 28 chart points above 4s'],['Global / worst 20s TPOT p99','17.394 / 52.658 ms'],['Individual TPOT tails','7 requests above 40ms; 3 above 80ms'],['CPU capture','Two nonblocking 10Hz recordings lasting 660s; Decode Python PID 1 and detokenizer PID 366'],['Capture quality','PID 1: 33,064 thread samples / 130 read errors; PID 366: 19,683 thread samples / 38 errors']])+'''<p>This is diagnostic evidence, not an uninstrumented performance acceptance run. Most main-thread samples ended at the native event-loop boundary; detokenizer samples mostly waited for input. The capture did not isolate a long Python loop. Native stacks were absent, and failed reads plus synthetic sample weights prevent exact wall-time attribution. No explicit GC sample does not rule out garbage collection.</p>
<p>The sampled serving path is the older Dynamo <code>request_handlers/llm/decode_handler.py</code>, not the colocated newer <code>llm_engine.py</code>. Active handler/main source files and hashes were preserved. Any startup-freeze proposal must be based on the active initialization path. <a href="analyze_output_profiles.py">CPU-sample analysis script</a>; private profiles are in <code>attempt21-output-delivery-diagnostic/cpu-stacks/</code>.</p>
<p><strong>ATT22 is a failed, interrupted trial:</strong> '''+reportlink('20260913_030350')+'''. Prefill scheduling size changed from 8,192 to 6,144 tokens with a matching graph bucket. Exact source, images, memory/cache settings, depth 1, output cap 20 and workload remained fixed. The initial recent p50 was about 1.8 seconds, but sustained Prefill backlog developed. Admissions stopped at 341.732 seconds. Of 3,289 admitted requests, 3,276 succeeded and 13 received HTTP 529 overload responses; 2,632 planned requests were intentionally not admitted.</p>'''+table(['ATT22 interrupted trial','Observed result'],[['Successful-request TTFT p50 / p99','4.627 / 17.139 seconds'],['Worst 20s completion TTFT p50','16.818 seconds at 357s; 202 samples; 218 chart points above 4s'],['Global / worst 20s TPOT p99','17.380 / 56.393 ms'],['Load generator','Valid; all admitted client outcomes accounted for'],['Residual serving state','13 pending Prefill bootstraps per PP rank after client completion; Decode and frontend client gauges idle'],['Recovery','Exact saved 8K recipe restored and Ready; retrieval correctness anomaly under investigation']])+'''<p>The 6K configuration did not sustain enough Prefill throughput at the fixed offered load. The frontend rejection/error counters increased by 13; sampled backend rejection counters did not increase. Residual Prefill bootstraps are consistent with the previously reported cleanup bug after overload. No cleanup fix is claimed.</p>
<p>The old drain watcher and all collectors were closed before recovery. The record explicitly distinguishes complete client drain from incomplete engine drain; the replacement worker cannot retroactively make the failed trial appear drained. The recovery diff restores only the three Prefill argument values. An initial preflight stopped before mutation because the default Kubernetes API schema differed from the chart schema; the corrected check reads the explicit API conversion.</p>
<p><a href="diagnostic-att21.json">ATT21 aggregate evidence</a> · <a href="negative-att22.json">ATT22 partial-run evidence</a> · <a href="prefill6k-values.json">Exact 6K values override</a>. The interrupted trial is excluded from the full-run comparison table. Its truncated percentiles are not directly comparable to complete ten-minute trials. Since the TPOT stall pattern predates the retained source patches, its unresolved root cause can take lower priority while testing the remaining TTFT spikes.</p>''')
section('recovery-correctness','Recovery retrieval anomaly: unresolved','''<div class="callout"><strong>Performance tuning is paused for a correctness investigation.</strong> After restoring the exact 8K configuration, the third synthetic retrieval probe generated repeated digits, reached its 256-token limit and produced no final answer. The first two probes returned the expected identifiers. This is preserved as a failed correctness check, not discarded as a short-budget test.</div>
<p>The worker is Ready with unchanged source/image hashes, fixed KV capacity and all four 8K graph captures. A fresh-cache repeat returned all three correct identifiers; its exact-text comparison differed only in whitespace. A later pass does not explain or erase the first failure. A predeclared five-trio series then passed all 15 requests after owned-cache resets, with exact input/cache coverage. These later passes do not establish the original cause. A source control restored both Prefill files to their exact frozen pre-optimization versions, keeping the 8K settings, other overlays, images and Decode/frontend containers fixed. Its predeclared series returned 14 correct answers out of 15. The first third-cold probe stopped after only one identifier, although all protocol completions and input/cache counts were correct; the following 12 requests passed. All four native 8K graphs executed. The retained patches are therefore not necessary for this fixture to exhibit a retrieval failure. The two observed failure modes differ, and these small series do not establish the exact cause or prove zero patch effect.</p>
<p>Private evidence: <code>/mnt/HPC/tom/pd-latency-followup-20260913/recovery-after-att22/retrieval-candidate.json</code>, <code>retrieval-repeat01-candidate.json</code>, and <code>retrieval-series-retained8k/</code>. The frozen control and all logs are under <code>attempt23-frozen-source-correctness/</code>. Existing successful latency runs remain valid observations of speed, but do not constitute comprehensive answer-correctness validation. Further diagnosis will distinguish KV transfer consistency from generation behavior; no full load run has been started on the frozen control.</p>''')
section('kv-boundary','A concrete KV handoff mismatch','''<div class="callout"><strong>ATT25 reproduced the third-request failure with a byte-level difference.</strong> Two retrieval answers were correct; the third cold request reached 256 tokens without a final answer. Its regular KV hashes differ between Prefill and Decode in global layers 58–77, exactly the last Prefill pipeline stage. No performance replay followed this finding.</div>
<p>The first two requests match all 156 logical pool tensors each. The failed request matches 136 of 156: all 78 DSA key/scale tensors match, while 20 regular KV tensors differ. The final 16 token rows match even in those 20 tensors; earlier Decode bytes contain substantially more zeros. Fifteen boundary snapshots join by exact internal request and bootstrap-room identity, covering about 3.0 GB of logical KV bytes. These observations suggest an early chunk read before its GPU writes complete, but do not yet establish the precise missing range or prove the cause.</p>
<p>Source inspection found a relevant existing dependency gap: with pipeline parallelism, this deployment disables the ordinary overlap scheduler. Its non-final chunk send can precede the prior forward-completion wait; the last pipeline rank lacks the proxy-send dependency present on the other ranks. ATT26 then added a broad producer-completion wait only to Prefill. All three answers were correct and all 468 compared pool tensors matched, while Decode and frontend remained unchanged. The expected zero hidden-state layout difference persisted. This supports the missing dependency as the cause of the observed KV mismatch; three requests with synchronous fingerprint diagnostics do not establish general correctness. ATT27 replaces the broad scheduler wait with a per-segment CUDA event consumed in Mooncake’s transfer thread, after outstanding-transfer accounting and before an abort/status recheck. Thirteen CPU fixtures execute the actual send, queue and worker methods. ATT27 also returned all three correct answers with all 468 pool tensor comparisons matching. Six prior Decode metadata files were hash-verified and excluded from this new trial. All queues drained. This change is not yet a validated performance result; the isolated Prefill151/Decode192 deployment subsequently passed all 15 predeclared retrieval requests with fingerprint capture disabled. This sequential correctness result is separate from sustained-load performance.</p>
<p>All observed metadata differences concern zero-filled hidden-state buffers with different layouts: 16 float32 values on Prefill versus 6,144 bfloat16 values on Decode. This difference appears on both passing and failing requests. The six other compared fields match. Zero speculative-seed validity remains a separate question; the layout difference alone is not evidence of random transport corruption.</p>
<p>ATT24 sent no probes. Before using its diagnostic, review found that the original DSA fingerprint helper included padding and omitted valid scale bytes on partial pages. A diagnostic-only correction passed twelve CPU fixtures, including a deliberately changed final scale byte that the original helper missed. An opt-in guard limits captures to the P/D boundary, preserving the existing EAGLE configuration without per-verify dumps. These are diagnostic changes, separate from the six retained performance changes.</p>
<p><a href="kv-boundary-att25.json">Aggregate comparison and limitations</a> · <a href="diagnostic-fingerprint.patch">Diagnostic helper patch</a>. Exact source hashes, CPU fixtures, rollout manifests, all request outcomes and snapshot archives are retained under <code>/mnt/HPC/tom/pd-latency-followup-20260913/attempt25-pd-only-kv-fingerprint/</code> and <code>candidates/dsa-snapshot-layout/</code>. Hashing synchronizes CUDA and may alter a race; these request timings are not performance evidence.</p>''')
section('expanded-goal','Expanded four-node investigation','''<p>Tom added nodes 151 and 192 to 130 and 132. The goal now includes a 2P1D deployment at about 60M input / 6M uncached TPM with the same roughly 90% hit rate, ten-minute measured duration, 20-token output cap and latency/speed requirements. The target remains every Alex 20-second completion-window TTFT p50 below 4 seconds, correct outputs and zero errors, with TPOT tails investigated separately.</p>
<p>Initial checks found all four GPUs idle on each new node; all sixteen GPUs share a healthy NVLink fabric. An isolated second 1P1D deployment was installed at 12:37 Singapore for Prefill151 / Decode192, with a private 600GiB Mooncake Store and frontend port 32109. All workers became Ready and the uninstrumented correctness control passed 15/15 requests, exact cache/input coverage, and all-rank 8K graph replay. ATT28 now rolls only Prefill151 to the six optimized source changes plus producer events on both send paths; Decode192, frontend and Store are unchanged. Sustained latency testing remains pending. The tentative final topology is Prefill132 + Prefill151 and one eight-GPU Decode spanning130 +192.</p>
<p>The fourth doubled-load selection is registered in Alex as <code>tom-capacity-v3-2p-60m-6m-10min-20260913</code>. It has 13,469 measured requests from1,254 sessions:600,193,610 input and59,992,906 modeled uncached tokens over600 seconds. Its400 distinct warmup requests add22,317,642 input tokens over120 seconds. Every one of72,325 numeric boundary probes passes the disclosed1% input/5% uncached whole-request tolerances. Sampled rolling minutes have at least335 exact16K prefix families; largest-family share is at most3.225%.</p>
<p>Alex Prepare <code>20260913_045325</code> finished at12:55:20 Singapore using16CPUworkers in112seconds, with no inference requests. All13,869 original payload frames were hash/decompression/JSON checked; all canonical bodies are distinct. Every prepared token sequence equals its verified original GLM5.3 source. Dataset ID:<code>dataset-dfa320022c5b1e8c171a2227</code>; token profile:<code>profile-0f6d63bca1c499991a2a2073</code>. The full-pack picker average51.878MTPM includes warmup; the measured schedule targets60M.</p>
<p>Runtime cache behavior is still unverified. The modeled two-Prefill configuration has11.102528M local tokens each and20M shared logical L3 tokens. Ten seconds of completion delay plus five seconds of L3 publication delay passes the round-robin audit; twenty seconds of total visibility delay fails. Actual Store byte capacity, routing, pinning and L3 hit partitioning require live checks. Earlier candidates remain recorded: candidate01 fails the five-second publication sensitivity; candidates02 and03 fail seven and two sampled numeric windows respectively. Candidate04 bounds cumulative uncached-token debt across minute boundaries; it does not retime failed windows after selection.</p>
<p><a href="optimized-event.patch">Producer-event patch on top of the six optimizations</a>. The deferred path records the event before launching later independent forward work. Thirteen actual-method transport fixtures,51 ownership/lifetime checks and six producer-boundary checks passed on CPU. The first uninstrumented control and this combined candidate have separate records; neither is a new best latency run.</p>
<p><a href="doubled-load-candidate-summary.json">Dataset counts, numeric audits and cache scenarios</a> · <a href="producer-fence-att26.json">ATT26 comparison</a> · <a href="producer-event-att27.json">ATT27 comparison</a> · <a href="async-kv-event.patch">ATT27 event-fence patch</a> · <a href="async-kv-event-cpu.json">Thirteen CPU fixtures</a>. Private manifests, source hashes, startup evidence and failed candidates are retained under <code>/mnt/HPC/tom/pd-latency-followup-20260913/expanded-four-node/</code> and <code>attempt27-async-kv-event/</code>.</p>''')
contract=json.loads((ROOT/'evidence/contract-percentiles.json').read_text())
contract_table=table(['Run','P50','P75','P90','P99','Mean'],[[reportlink(r['run_id'])]+[f"{r['ttft_seconds'][str(p)]:.3f} s" for p in [50,75,90,99]]+[f"{r['ttft_mean']:.3f} s"] for r in contract])
section('contract','Contract figures and current compliance limits','''<p>Tom clarified the column order as Metric, P50, P75, P90, P99, Average. The supplied TTFT targets map to 4 / 8 / 12 / 30 seconds; no average value was supplied. The stated contract tolerance is less than 1.2 times those targets. We retain the stricter research objective of short-window p50 below 4 seconds.</p>
<p>Both final runs meet all four supplied whole-run TTFT targets even before the 1.2 multiplier. This does not replace the stricter short-window research goal.</p>'''+contract_table+'''<p>The supplied speed/latency pairs are 55 tokens/s ↔ 18 ms, 30 ↔ 33 ms, and 25 ↔ 40 ms, with a speed-retention requirement above 90%. Three pairs do not fully populate the five columns. Direct OTPS percentile order reverses when converted to TPOT, and rounded reciprocals should not be treated as exact same-percentile identities. No complete contract certification is claimed yet.</p>'''+table(['ATT20 raw request metric','Observed'],[['TTFT ≤ 4 s','96.10% of successful requests'],['TPOT ≤ 18 ms','5,880 / 5,921 = 99.31%'],['TPOT ≤ 33 ms','5,911 / 5,921 = 99.83%'],['TPOT ≤ 40 ms','5,911 / 5,921 = 99.83%']])+'''<p>These are descriptive fractions using the client metric, not a reinterpretation of the contract. A request-fraction criterion and a requirement on every short-window p99 are different requirements.</p>''')
rows=[]
for r in data['runs']:
 rows.append([esc(r['arm'].replace('_',' ')),reportlink(r['run_id']),str(r['successes'])+' / '+str(r['failures']),f"{r['ttft_global_ms']['p50']/1000:.3f}",f"{r['worst_portal_ttft']['ttft']['p50']/1000:.3f}",f"{r['tpot_global_ms']['p99']:.2f}",f"{r['worst_portal_tpot']['tpot']['p99']:.2f}",str(r['tpot_requests_above40'])])
section('results','All uninstrumented completed comparisons',table(['Arm','Alex report','Success / fail','TTFT p50 s','Max 20s p50 s','TPOT p99 ms','Max 20s p99 ms','TPOT >40 ms requests'],rows)+'''<p><a href="latency-comparison.json">Download the aggregate evidence</a> · <a href="analyze_latency.py">Independent reconstruction script</a>. Script input timing exports remain in the private research directory; they contain request identifiers and are intentionally not embedded here.</p>''')
section('attempts','Diagnostics, failed approaches and retained history','''<p>The investigation contains 21 attempt directories and 18 completed ten-minute trials: 14 uninstrumented trials, four diagnostics, one interrupted diagnostic, one startup failure and one warmup-only anomaly. The preceding baseline is separate.</p>'''+table(['Attempt','Purpose / result'],[
['01','Bounded GPU diagnostic interrupted after profiler export disruption and a native-hash thread fault. Not an acceptance run; scoped Prefill recovery retained.'],
['02 / 03','Depth 1, then breakable CUDA graphs. Still accumulated backlog and rejected requests.'],
['04','CPU diagnostic: low OS runqueue wait weakened CPU scheduling starvation as the main explanation.'],
['05 / 06','Earlier control bundle, then depth 0. Depth 0 worsened sustained throughput.'],
['07 / 08','Launch before old-output handling, then enable breakable graphs on that source. Improvement, but still failures.'],
['09 / 10','Trace verbosity and 27-phase CPU timing diagnostics. Timing measures include synchronization waits.'],
['11','Earlier last-rank output: first full zero-failure run, but sustained TTFT still high.'],
['12','Earlier current-proxy publication failed startup through a lazy NCCL CPU-metadata wait cycle; rolled back.'],
['13','Control-safe proxy variant completed but regressed latency; excluded from best lineage.'],
['14 / 15','Early cached prefix and all-rank output relay tested separately. Prefix improved latency; all-rank relay alone did not.'],
['16 / 16b','Combined changes. First warmup had one missing-TTFT/empty-visible-output event; one predeclared fresh-reset retry completed. Original anomaly remains unresolved.'],
['17 / 18','Final-map reuse, then 30-phase diagnostic; page-map dependency wait motivated overlap work.'],
['19 / 20','Same-iteration map-copy overlap; unchanged fresh-cache repeat. Both pass the original 60s criterion, both retain shorter-window spikes.'],
])+'''<p>Historical counters recorded no quota throttling in the experiment containers or immediate pod parents. Sampled scheduler-main-thread runqueue wait was very small; this does not exclude locks, the GIL, synchronization or serial work. Initial queue growth was visible in Prefill before Decode saturation. Late Decode-forward means stayed near 0.2 seconds, while Prefill waiting grew markedly in early unsuccessful arms.</p>
<p>Observed bootstrap/final-transfer means in the final runs remain about 0.58 / 0.60 seconds. The original roughly 1.2-second handoff delays were reduced, not eliminated. The separate Decode-rejection cleanup issue was filed and deferred; successful runs do not prove it fixed.</p>''')
section('validation','Correctness checks and evidence limits','''<ul><li>51 CPU lifetime, payload and cursor checks; four deliberately unsafe variants rejected.</li><li>30 actual-loop ordering cases and two complete source/AST restoration checks.</li><li>Native CUDA copy semantics and graph/map-path activation on all four Prefill ranks.</li><li>Three long-context retrieval probes: two cold and one shared-prefix case. Final answers, payload hashes and input/cache counts matched. Reasoning text and output lengths varied; bitwise or token-level equivalence was not established.</li><li>Each final run: zero failures, no empty successful outputs, DONE observed, all TTFT values present, valid generator, 22 observed rejection/error counter series without increments, 56 queue/running gauges idle twice, three bound containers Ready with zero restarts.</li></ul>
<p>Correctness retrieval probes used up to 256 output tokens; the canonical performance workload remained capped at 20. Histories retain the failed short-budget probe and warmup anomaly. Missing counters remain unobserved, not zero. Trace requery recovered three later-visible spans; both query sets were saved. Startup evidence after log rotation was inherited only for the unchanged container, while current identities and source/spec hashes were rechecked.</p>''')
section('reproduce','Reproduction and rollback record','''<p>Use the following private paths on Tom’s shared workspace as artifact locators. They are not browser links. The original archive is the complete record; this public page contains the report, reviewed patch and selected non-secret validation artifacts.</p>'''+table(['Artifact','Private locator'],[
['Complete investigation',code(OLD)],['Follow-up',code(ROOT)],['Frozen SGLang base',code('/mnt/HPC/tom/experiments/glm53-optim-exp-1p1d/sources/sglang-6d08e28b0c0691899973e3f11bf01fdbdf192a63')],
['Final candidate',code(str(candidate))],['Best exact Helm recipe',code('attempt19-same-iteration-map-copy/rollout/PREPARED.json')],['Best chart and ordered values',code('attempt19-same-iteration-map-copy/chart/')+'; '+code('rollout/before-values.json')+' then '+code('rollout/trial-values.json')],
['Expected deployment',code('attempt19-same-iteration-map-copy/rollout/after-render.yaml')],['Run and validation records',code('attempt19-same-iteration-map-copy/REPORT.md')+' / '+code('attempt20-map-copy-repeat/REPORT.md')],
['Every attempt','Original root: '+code('EXPERIMENT-INDEX.md')+', '+code('DECISION-LEDGER.md')+', '+code('BEST-RUN-SETTINGS.md')],
['Raw portal events',code('/var/lib/replay/results/<run-id>/details/raw_events.jsonl')+' in the Alex pod'],
['New timing exports',code(str(ROOT/'evidence/<run-id>/timing-events.jsonl'))],
['Historical CPU audit',code('/mnt/HPC/tom/ttft-bootstrap-handoff-20260911.yhMGqD/saved-evidence/historical-cpu-arithmetic/REPORT.md')],
['Complete archive',code('settings-retention-20260913-061635.tar.gz')+' under the original root'],
['Archive SHA-256',code('5d59acb2fbabd8dd4552202f68331eb17c26c91ad9bf2929459259cd672091f3')],
])+'''<p>The final archive verified 2,113 checksummed files across 21 attempt directories; the preserved chart and ordered values reproduced the recorded render byte-for-byte. Its dependencies include model data, images, credentials and pre-existing overlays; the archive is not a standalone runnable container.</p>
<ol><li>Check current cluster, namespace, Helm owner, node placement, bound pod/container identities, source hashes and idle queues. The owned release is <code>maas-dev-tom/glm53-optim-exp-1p1d</code>.</li><li>Verify the archive and frozen sources. Apply the cumulative patch only against its recorded base; the saved temporary-directory apply check reconstructed both candidate files exactly.</li><li>Render the owned chart with the recorded values in order. Inspect the complete diff and retain the current rollback recipe before applying a scoped change. Historical commands carry old identities and must not be replayed blindly.</li><li>Verify Ready containers, exact source/image hashes, all-rank graph activation, fixed cache capacity and retrieval correctness. Retain the other runtime overlays.</li><li>Clear only the owned caches, run the canonical 100-request warmup and require all TTFTs, then run the full 5,921-request replay through Linux headless CDP 19341. The maintained helper is <code>/mnt/HPC/tom/.local/share/alex-headless/cdp.mjs</code>.</li><li>Collect raw timing events, live metrics, generator diagnostics, trace joins and exact clocks. Audit both 20s completion and 60s arrival windows, whole-run percentiles, TPOT tails and failures.</li><li>Drain queues, close owned collectors and preserve the outcome even on regression. Use the recorded prior chart/values for rollback after fresh ownership checks.</li></ol>
<p>Reproduction script: <code>python3 worker/analyze_latency.py</code> from this follow-up record. It reconstructs all saved chart TTFT p50 and TPOT p99 points and verifies them against the exported portal timeseries, rather than assuming the labels describe the same population.</p>''')
section('provenance','Image, source and publication provenance',table(['Component','Immutable identity'],[
['SGLang frozen commit',code('6d08e28b0c0691899973e3f11bf01fdbdf192a63')],
['Final PP scheduler SHA-256',code('b3b95b176a6185a34b75664cda8aecc921989b9e50fa5efea268d3e207c07d41')],
['Final Prefill SHA-256',code('eb8ccfa08e3e5373d47123ed5fb74d4a19b84b00c9ab1025b9875033dc2bc372')],
['Cumulative patch SHA-256',code('d004b159163dedaee15ddb3a0ecf91cea1e171fab9b0e77b156a0989cbb3a531')],
['Worker image digest',code('sha256:21bee33e6e20c10481d84d660e03b4675d5ff817ce2cd0a4cc859eb9e1ae62e0')],
['Frontend image digest',code('sha256:8ab5025a0233062fa6224b345e2ac22a65e823d40f4dcd6242128afc491440b5')],
['Preserved generator commit',code('a50880df29554b03a2cf6d455abf9dfb4576ad27')],
['Deployed benchmark source SHA-256',code('2f5767eb8e54779ab171ef3e2bb27f4464e29d1f9c5acd4c94a9d8b2afce2af2')],
['Authoring source',code(str(Path(__file__).resolve()))],
])+'''<p>The shared generator checkout has a legacy remote and an unrelated local modification; it was not pulled or mutated for this comparison. Its benchmark source matched the deployed file byte-for-byte. The first timing export connection interrupted during ATT20; the partial file was retained and ATT20 was re-exported completely. All 15 final timing exports contain exactly 5,921 records.</p>''')
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f7fa;color:#1b2939;font:16px/1.65 system-ui,sans-serif}header{background:#142a40;color:white;padding:28px 40px}header a{color:#c5e3f8}header h1{font-size:32px;margin:8px 0}header p{max-width:1000px;color:#c7d5e5;margin:5px 0}.layout{display:grid;grid-template-columns:225px minmax(0,1120px);gap:32px;max-width:1435px;margin:28px auto;padding:0 22px}aside{position:sticky;top:20px;align-self:start;border-left:3px solid #cbd7e3;padding:12px 15px;background:#edf2f6}aside a{display:block;font-size:13px;padding:5px 0;text-decoration:none;color:#425a70}article{min-width:0}section{background:white;padding:25px 30px;margin-bottom:22px;border:1px solid #dce4eb;border-radius:9px;scroll-margin-top:18px}h2{font-size:25px;margin:0 0 15px}h3{font-size:17px;margin:0 0 8px}p{margin:12px 0}a{color:#11698b}code{font:12px/1.6 ui-monospace,monospace;background:#eff3f6;padding:2px 4px;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;vertical-align:top;padding:10px 12px;border-bottom:1px solid #dfe6ed}th{background:#eef3f7;color:#365064}tbody tr:nth-child(even){background:#fafbfc}.table-scroll{overflow-x:auto}.callout{padding:16px 20px;border-left:4px solid #bf6c27;background:#fff6e9}.equation{display:flex;flex-wrap:wrap;gap:14px;align-items:center;padding:17px;background:#eef4f8;border-radius:6px}.unit{color:#587186;font-size:13px}select{max-width:100%;padding:8px;border:1px solid #b7c9d8;border-radius:5px;font:14px system-ui}.chart-card{padding:18px;border:1px solid #dfe6ed;margin-top:16px;border-radius:6px}svg{display:block;width:100%;height:auto}footer{color:#607387;margin:20px 0}li{margin:7px 0}'''
js='''const DATA=JSON.parse(document.getElementById('chart-data').textContent),sel=document.getElementById('run-select');function draw(){const p=DATA[sel.value].points;for(const [id,col,scale,threshold,unit,color] of [['ttft-chart',1,1000,4,'s','#166b8e'],['tpot-chart',2,1,40,'ms','#9b4c2d']]){const svg=document.getElementById(id),max=Math.max(threshold*1.3,...p.filter(x=>x[col]!=null).map(x=>x[col]/scale))*1.08,end=Math.max(...p.map(x=>x[0])),X=t=>50+825*t/end,Y=v=>215-190*v/max;let s='';for(let i=0;i<=4;i++){const v=max*i/4;s+=`<line x1="50" x2="875" y1="${Y(v)}" y2="${Y(v)}" stroke="#e1e8ee"/><text x="43" y="${Y(v)+4}" text-anchor="end" font-size="11" fill="#556b7d">${v.toFixed(1)}</text>`}for(let t=0;t<=end;t+=120)s+=`<text x="${X(t)}" y="239" text-anchor="middle" font-size="11" fill="#556b7d">${t}s</text>`;s+=`<line x1="50" x2="875" y1="${Y(threshold)}" y2="${Y(threshold)}" stroke="#b54032" stroke-dasharray="5 4"/><text x="870" y="${Y(threshold)-5}" text-anchor="end" font-size="11" fill="#b54032">${threshold} ${unit}</text>`;s+=`<polyline fill="none" stroke="${color}" stroke-width="2" points="${p.filter(x=>x[col]!=null).map(x=>X(x[0])+','+Y(x[col]/scale)).join(' ')}"/>`;svg.innerHTML=s;svg.onmousemove=e=>{const rect=svg.getBoundingClientRect(),t=((e.clientX-rect.left)/rect.width*900-50)/825*end,q=p.reduce((a,b)=>Math.abs(b[0]-t)<Math.abs(a[0]-t)?b:a);document.getElementById('point-readout').textContent=`${sel.value} · elapsed ${q[0]} s · TTFT p50 ${q[1]==null?'N/A':(q[1]/1000).toFixed(3)+' s'} · TPOT p99 ${q[2]==null?'N/A':q[2].toFixed(2)+' ms'}`}}}sel.onchange=draw;draw();'''
nav=''.join('<a href="#'+id+'">'+esc(title)+'</a>' for id,title,_ in sections)
body=''.join('<section id="'+id+'"><h2>'+esc(title)+'</h2>'+content+'</section>' for id,title,content in sections)
now=datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).strftime('%Y-%m-%d %H:%M Singapore')
page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Reproducible GLM-5.3 GB300 TTFT and TPOT optimization investigation, all trial outcomes, source patch and corrected short-window acceptance."><title>GLM-5.3 GB300: TTFT and TPOT investigation</title><style>'+css+'</style></head><body><header><a href="../">MaaS Docs</a><h1>GLM-5.3 GB300: TTFT and TPOT investigation</h1><p>30M input / 3M uncached TPM · code, evidence and reproduction record</p><p>Updated '+now+' · research active · all times Singapore unless explicitly UTC</p></header><div class="layout"><aside aria-label="Contents">'+nav+'</aside><article>'+body+'<footer>Generated from preserved experiment artifacts. Open issues and negative results remain part of the record.</footer></article></div><script type="application/json" id="chart-data">'+json.dumps(chart_data).replace('</','<\\/')+'</script><script>'+js+'</script></body></html>'
(OUT/'index.html').write_text(page)
print(json.dumps({'output':str(OUT),'sections':len(sections),'bytes':len(page.encode()),'public_url':'https://tomyoung903.github.io/maas_docs/'+OUT.name+'/'}))
